
MODULE exit INPUT.
  save_code = ok_code.
  CLEAR ok_code.

  CASE save_code.
    WHEN 'BACK' OR 'CANCEL'.
      LEAVE TO SCREEN 0.
    WHEN 'EXIT'.
      LEAVE PROGRAM.
  ENDCASE.
ENDMODULE.                 " EXIT  INPUT

*&---------------------------------------------------------------------*
*&      Module  GET_OK_CODE  INPUT
*&---------------------------------------------------------------------*
MODULE get_ok_code INPUT.
  save_code = ok_code.
  CLEAR ok_code.
ENDMODULE.                 " GET_OK_CODE  INPUT

*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_0010  INPUT
*&---------------------------------------------------------------------*
MODULE user_command_0010 INPUT.
  CASE save_code.

*   ===== TAMBAHAN BARU: DOWNLOAD TEMPLATE =====
    WHEN 'ZDLTPL'.
      PERFORM download_template.
*   ===== END TAMBAHAN =====

    WHEN 'EXECUTE'.
      IF RMATERIAL IS NOT INITIAL.
        REFRESH: I_MASTER_UPL, I_KLAH, I_KSML, I_CABN, ERR_TAB.

        FILENAME = UP_FILE.
        DATA : IT_TYPE   TYPE TRUXS_T_TEXT_DATA.

        CALL FUNCTION 'TEXT_CONVERT_XLS_TO_SAP'
         EXPORTING
          I_LINE_HEADER        = 'X'
          I_TAB_RAW_DATA       = IT_TYPE
          I_FILENAME           = P_INFILE2
         TABLES
          I_TAB_CONVERTED_DATA = I_MASTER_UPL[]
         EXCEPTIONS
          CONVERSION_FAILED    = 1
          OTHERS               = 2.
        IF SY-SUBRC NE 0.
          MESSAGE ID SY-MSGID
            TYPE SY-MSGTY
            NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
        ENDIF.

        DELETE ADJACENT DUPLICATES FROM I_MASTER_UPL COMPARING MATNR.

        IF I_MASTER_UPL[] IS NOT INITIAL.
          SELECT * FROM KLAH INTO CORRESPONDING FIELDS OF TABLE I_KLAH
            FOR ALL ENTRIES IN I_MASTER_UPL
            WHERE KLART EQ '023'
              AND CLASS EQ I_MASTER_UPL-CLASS.
          IF I_KLAH[] IS NOT INITIAL.
            SELECT * FROM KSML INTO CORRESPONDING FIELDS OF TABLE I_KSML
              FOR ALL ENTRIES IN I_KLAH
              WHERE CLINT EQ I_KLAH-CLINT
                AND KLART EQ '023'.
            IF I_KSML[] IS NOT INITIAL.
              SELECT * FROM CABN INTO CORRESPONDING FIELDS OF TABLE I_CABN
                FOR ALL ENTRIES IN I_KSML
                WHERE ATINN EQ I_KSML-IMERK.
            ENDIF.
          ENDIF.
        ENDIF.

        LOOP AT I_MASTER_UPL INTO WA_MASTER_UPL.
          REFRESH: RETURNMES, MATERIALDESCRIPTION, UNITSOFMEASURE,
                   UNITSOFMEASUREX, TAXCLASSIFICATIONS, INSPECTIONCTRL.
          CLEAR  : HEADDATA, CLIENTDATA, CLIENTDATAX, RETURN,
                   WA_MATERIALDESCRIPTION, WA_UNITSOFMEASURE,
                   WA_UNITSOFMEASUREX, PLANTDATA, PLANTDATAX,
                   SALESDATA, SALESDATAX, WA_TAXCLASSIFICATIONS,
                   VALUATIONDATA, VALUATIONDATAX, GW_INSPECTIONCTRL,
                   WA_ERR_TAB.

          IF ( WA_MASTER_UPL-CLASS IS NOT INITIAL
           AND ( WA_MASTER_UPL-WARNA IS NOT INITIAL
              OR WA_MASTER_UPL-VOL_PROD IS NOT INITIAL ) )
           AND WA_MASTER_UPL-KZWSM IS NOT INITIAL.
            WA_ERR_TAB-MATNR    = WA_MASTER_UPL-MATNR.
            WA_ERR_TAB-ZERR_LOG = TEXT-E01.
            APPEND WA_ERR_TAB TO ERR_TAB.
            CLEAR WA_ERR_TAB.
            CONTINUE.
          ENDIF.

          IF WA_MASTER_UPL-MATNR IS INITIAL
          OR WA_MASTER_UPL-MBRSH IS INITIAL
          OR WA_MASTER_UPL-MTART IS INITIAL.
            WA_ERR_TAB-MATNR    = WA_MASTER_UPL-MATNR.
            WA_ERR_TAB-ZERR_LOG = TEXT-E03.
            APPEND WA_ERR_TAB TO ERR_TAB.
            CLEAR WA_ERR_TAB.
            CONTINUE.
          ENDIF.

          IF WA_MASTER_UPL-WERKS IS INITIAL.
            WA_ERR_TAB-MATNR    = WA_MASTER_UPL-MATNR.
            WA_ERR_TAB-ZERR_LOG = TEXT-E04.
            APPEND WA_ERR_TAB TO ERR_TAB.
            CLEAR WA_ERR_TAB.
            CONTINUE.
          ENDIF.

          IF WA_MASTER_UPL-LGORT IS INITIAL.
            WA_ERR_TAB-MATNR    = WA_MASTER_UPL-MATNR.
            WA_ERR_TAB-ZERR_LOG = TEXT-E05.
            APPEND WA_ERR_TAB TO ERR_TAB.
            CLEAR WA_ERR_TAB.
            CONTINUE.
          ENDIF.

          IF SY-MANDT EQ 300.
            IF WA_MASTER_UPL-PRCTR IS INITIAL.
              WA_ERR_TAB-MATNR    = WA_MASTER_UPL-MATNR.
              WA_ERR_TAB-ZERR_LOG = TEXT-E06.
              APPEND WA_ERR_TAB TO ERR_TAB.
              CLEAR WA_ERR_TAB.
              CONTINUE.
            ENDIF.
          ENDIF.

          CALL FUNCTION 'CONVERSION_EXIT_MATN1_INPUT'
            EXPORTING INPUT        = WA_MASTER_UPL-MATNR
            IMPORTING OUTPUT       = HEADDATA-MATERIAL_LONG
            EXCEPTIONS LENGTH_ERROR = 1 OTHERS = 2.

          HEADDATA-IND_SECTOR    = WA_MASTER_UPL-MBRSH.
          HEADDATA-MATL_TYPE     = WA_MASTER_UPL-MTART.
          HEADDATA-BASIC_VIEW    = 'X'.
          HEADDATA-PURCHASE_VIEW = 'X'.

          IF SY-MANDT EQ 300.
            IF WA_MASTER_UPL-WERKS IS NOT INITIAL
            AND WA_MASTER_UPL-LGORT IS NOT INITIAL
            AND WA_MASTER_UPL-PRCTR IS NOT INITIAL.
              HEADDATA-STORAGE_VIEW = 'X'.
            ENDIF.
          ELSE.
            IF WA_MASTER_UPL-WERKS IS NOT INITIAL
            AND WA_MASTER_UPL-LGORT IS NOT INITIAL.
              HEADDATA-STORAGE_VIEW = 'X'.
            ENDIF.
          ENDIF.

          IF WA_MASTER_UPL-MATKL IS NOT INITIAL.
            CLIENTDATA-MATL_GROUP  = WA_MASTER_UPL-MATKL.
            CLIENTDATAX-MATL_GROUP = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-BISMT IS NOT INITIAL.
            CLIENTDATA-OLD_MAT_NO  = WA_MASTER_UPL-BISMT.
            CLIENTDATAX-OLD_MAT_NO = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-MEINS IS NOT INITIAL.
            CALL FUNCTION 'CONVERSION_EXIT_CUNIT_INPUT'
              EXPORTING INPUT          = WA_MASTER_UPL-MEINS
              IMPORTING OUTPUT         = CLIENTDATA-BASE_UOM
              EXCEPTIONS UNIT_NOT_FOUND = 1 OTHERS = 2.
            CLIENTDATA-BASE_UOM_ISO  = CLIENTDATA-BASE_UOM.
            CLIENTDATAX-BASE_UOM     = 'X'.
            CLIENTDATAX-BASE_UOM_ISO = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-NTGEW IS NOT INITIAL.
            CLIENTDATA-NET_WEIGHT  = WA_MASTER_UPL-NTGEW.
            CLIENTDATAX-NET_WEIGHT = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-KZWSM IS NOT INITIAL.
            CLIENTDATA-UOMUSAGE  = WA_MASTER_UPL-KZWSM.
            CLIENTDATAX-UOMUSAGE = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-GEWEI IS NOT INITIAL.
            CALL FUNCTION 'CONVERSION_EXIT_CUNIT_INPUT'
              EXPORTING INPUT          = WA_MASTER_UPL-GEWEI
              IMPORTING OUTPUT         = CLIENTDATA-UNIT_OF_WT
              EXCEPTIONS UNIT_NOT_FOUND = 1 OTHERS = 2.
            CLIENTDATA-UNIT_OF_WT_ISO  = CLIENTDATA-UNIT_OF_WT.
            CLIENTDATAX-UNIT_OF_WT     = 'X'.
            CLIENTDATAX-UNIT_OF_WT_ISO = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-MTPOS_MARA IS NOT INITIAL.
            CLIENTDATA-ITEM_CAT  = WA_MASTER_UPL-MTPOS_MARA.
            CLIENTDATAX-ITEM_CAT = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-SPART IS NOT INITIAL.
            CLIENTDATA-DIVISION  = WA_MASTER_UPL-SPART.
            CLIENTDATAX-DIVISION = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-GROES IS NOT INITIAL.
            CLIENTDATA-SIZE_DIM  = WA_MASTER_UPL-GROES.
            CLIENTDATAX-SIZE_DIM = 'X'.
          ENDIF.

          CALL FUNCTION 'CONVERSION_EXIT_CUNIT_INPUT'
            EXPORTING INPUT          = WA_MASTER_UPL-MEINS
            IMPORTING OUTPUT         = WA_UNITSOFMEASURE-ALT_UNIT
            EXCEPTIONS UNIT_NOT_FOUND = 1 OTHERS = 2.
          WA_UNITSOFMEASUREX-ALT_UNIT     = WA_UNITSOFMEASURE-ALT_UNIT.
          WA_UNITSOFMEASURE-ALT_UNIT_ISO  = WA_UNITSOFMEASURE-ALT_UNIT.
          WA_UNITSOFMEASUREX-ALT_UNIT_ISO = WA_UNITSOFMEASURE-ALT_UNIT_ISO.

          IF WA_MASTER_UPL-BRGEW IS NOT INITIAL.
            WA_UNITSOFMEASURE-GROSS_WT  = WA_MASTER_UPL-BRGEW.
            WA_UNITSOFMEASUREX-GROSS_WT = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-GEWEI IS NOT INITIAL.
            CALL FUNCTION 'CONVERSION_EXIT_CUNIT_INPUT'
              EXPORTING INPUT          = WA_MASTER_UPL-GEWEI
              IMPORTING OUTPUT         = WA_UNITSOFMEASURE-UNIT_OF_WT
              EXCEPTIONS UNIT_NOT_FOUND = 1 OTHERS = 2.
            WA_UNITSOFMEASURE-UNIT_OF_WT_ISO  = WA_UNITSOFMEASURE-UNIT_OF_WT.
            WA_UNITSOFMEASUREX-UNIT_OF_WT     = 'X'.
            WA_UNITSOFMEASUREX-UNIT_OF_WT_ISO = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-VOLUM IS NOT INITIAL.
            WA_UNITSOFMEASURE-VOLUME  = WA_MASTER_UPL-VOLUM.
            WA_UNITSOFMEASUREX-VOLUME = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-VOLEH IS NOT INITIAL.
            CALL FUNCTION 'CONVERSION_EXIT_CUNIT_INPUT'
              EXPORTING INPUT          = WA_MASTER_UPL-VOLEH
              IMPORTING OUTPUT         = WA_UNITSOFMEASURE-VOLUMEUNIT
              EXCEPTIONS UNIT_NOT_FOUND = 1 OTHERS = 2.
            WA_UNITSOFMEASURE-VOLUMEUNIT_ISO  = WA_MASTER_UPL-VOLEH.
            WA_UNITSOFMEASUREX-VOLUMEUNIT     = 'X'.
            WA_UNITSOFMEASUREX-VOLUMEUNIT_ISO = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-LAENG IS NOT INITIAL.
            WA_UNITSOFMEASURE-LENGTH  = WA_MASTER_UPL-LAENG.
            WA_UNITSOFMEASUREX-LENGTH = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-BREIT IS NOT INITIAL.
            WA_UNITSOFMEASURE-WIDTH  = WA_MASTER_UPL-BREIT.
            WA_UNITSOFMEASUREX-WIDTH = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-HOEHE IS NOT INITIAL.
            WA_UNITSOFMEASURE-HEIGHT  = WA_MASTER_UPL-HOEHE.
            WA_UNITSOFMEASUREX-HEIGHT = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-MEABM IS NOT INITIAL.
            CALL FUNCTION 'CONVERSION_EXIT_CUNIT_INPUT'
              EXPORTING INPUT          = WA_MASTER_UPL-MEABM
              IMPORTING OUTPUT         = WA_UNITSOFMEASURE-UNIT_DIM
              EXCEPTIONS UNIT_NOT_FOUND = 1 OTHERS = 2.
            WA_UNITSOFMEASURE-UNIT_DIM_ISO  = WA_MASTER_UPL-MEABM.
            WA_UNITSOFMEASUREX-UNIT_DIM     = 'X'.
            WA_UNITSOFMEASUREX-UNIT_DIM_ISO = 'X'.
          ENDIF.

          APPEND WA_UNITSOFMEASURE  TO UNITSOFMEASURE.
          APPEND WA_UNITSOFMEASUREX TO UNITSOFMEASUREX.
          CLEAR  WA_UNITSOFMEASURE.
          CLEAR  WA_UNITSOFMEASUREX.

          IF WA_MASTER_UPL-MEINH IS NOT INITIAL.
            CALL FUNCTION 'CONVERSION_EXIT_CUNIT_INPUT'
              EXPORTING INPUT          = WA_MASTER_UPL-MEINH
              IMPORTING OUTPUT         = WA_UNITSOFMEASURE-ALT_UNIT
              EXCEPTIONS UNIT_NOT_FOUND = 1 OTHERS = 2.
            WA_UNITSOFMEASUREX-ALT_UNIT     = WA_UNITSOFMEASURE-ALT_UNIT.
            WA_UNITSOFMEASURE-ALT_UNIT_ISO  = WA_UNITSOFMEASURE-ALT_UNIT.
            WA_UNITSOFMEASUREX-ALT_UNIT_ISO = WA_UNITSOFMEASURE-ALT_UNIT_ISO.
            IF WA_MASTER_UPL-UMREZ IS NOT INITIAL.
              WA_UNITSOFMEASURE-NUMERATOR  = WA_MASTER_UPL-UMREZ.
              WA_UNITSOFMEASUREX-NUMERATOR = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-UMREN IS NOT INITIAL.
              WA_UNITSOFMEASURE-DENOMINATR  = WA_MASTER_UPL-UMREN.
              WA_UNITSOFMEASUREX-DENOMINATR = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-BRGEW IS NOT INITIAL.
              WA_UNITSOFMEASURE-GROSS_WT  = WA_MASTER_UPL-BRGEW.
              WA_UNITSOFMEASUREX-GROSS_WT = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-GEWEI IS NOT INITIAL.
              CALL FUNCTION 'CONVERSION_EXIT_CUNIT_INPUT'
                EXPORTING INPUT          = WA_MASTER_UPL-GEWEI
                IMPORTING OUTPUT         = WA_UNITSOFMEASURE-UNIT_OF_WT
                EXCEPTIONS UNIT_NOT_FOUND = 1 OTHERS = 2.
              WA_UNITSOFMEASURE-UNIT_OF_WT_ISO  = WA_UNITSOFMEASURE-UNIT_OF_WT.
              WA_UNITSOFMEASUREX-UNIT_OF_WT     = 'X'.
              WA_UNITSOFMEASUREX-UNIT_OF_WT_ISO = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-VOLUM IS NOT INITIAL.
              WA_UNITSOFMEASURE-VOLUME  = WA_MASTER_UPL-VOLUM.
              WA_UNITSOFMEASUREX-VOLUME = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-VOLEH IS NOT INITIAL.
              CALL FUNCTION 'CONVERSION_EXIT_CUNIT_INPUT'
                EXPORTING INPUT          = WA_MASTER_UPL-VOLEH
                IMPORTING OUTPUT         = WA_UNITSOFMEASURE-VOLUMEUNIT
                EXCEPTIONS UNIT_NOT_FOUND = 1 OTHERS = 2.
              WA_UNITSOFMEASURE-VOLUMEUNIT_ISO  = WA_MASTER_UPL-VOLEH.
              WA_UNITSOFMEASUREX-VOLUMEUNIT     = 'X'.
              WA_UNITSOFMEASUREX-VOLUMEUNIT_ISO = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-LAENG IS NOT INITIAL.
              WA_UNITSOFMEASURE-LENGTH  = WA_MASTER_UPL-LAENG.
              WA_UNITSOFMEASUREX-LENGTH = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-BREIT IS NOT INITIAL.
              WA_UNITSOFMEASURE-WIDTH  = WA_MASTER_UPL-BREIT.
              WA_UNITSOFMEASUREX-WIDTH = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-HOEHE IS NOT INITIAL.
              WA_UNITSOFMEASURE-HEIGHT  = WA_MASTER_UPL-HOEHE.
              WA_UNITSOFMEASUREX-HEIGHT = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-MEABM IS NOT INITIAL.
              CALL FUNCTION 'CONVERSION_EXIT_CUNIT_INPUT'
                EXPORTING INPUT          = WA_MASTER_UPL-MEABM
                IMPORTING OUTPUT         = WA_UNITSOFMEASURE-UNIT_DIM
                EXCEPTIONS UNIT_NOT_FOUND = 1 OTHERS = 2.
              WA_UNITSOFMEASURE-UNIT_DIM_ISO  = WA_MASTER_UPL-MEABM.
              WA_UNITSOFMEASUREX-UNIT_DIM     = 'X'.
              WA_UNITSOFMEASUREX-UNIT_DIM_ISO = 'X'.
            ENDIF.
            APPEND WA_UNITSOFMEASURE  TO UNITSOFMEASURE.
            APPEND WA_UNITSOFMEASUREX TO UNITSOFMEASUREX.
            CLEAR  WA_UNITSOFMEASURE.
            CLEAR  WA_UNITSOFMEASUREX.
          ENDIF.

          WA_MATERIALDESCRIPTION-LANGU     = SY-LANGU.
          WA_MATERIALDESCRIPTION-MATL_DESC = WA_MASTER_UPL-MAKTX.
          APPEND WA_MATERIALDESCRIPTION TO MATERIALDESCRIPTION.
          CLEAR  WA_MATERIALDESCRIPTION.

          PLANTDATA-PLANT  = WA_MASTER_UPL-WERKS.
          PLANTDATAX-PLANT = WA_MASTER_UPL-WERKS.
          STORAGELOCATIONDATA-PLANT     = WA_MASTER_UPL-WERKS.
          STORAGELOCATIONDATA-STGE_LOC  = WA_MASTER_UPL-LGORT.
          STORAGELOCATIONDATAX-PLANT    = WA_MASTER_UPL-WERKS.
          STORAGELOCATIONDATAX-STGE_LOC = WA_MASTER_UPL-LGORT.

          IF SY-MANDT EQ 300.
            IF WA_MASTER_UPL-PRCTR IS NOT INITIAL.
              CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
                EXPORTING INPUT  = WA_MASTER_UPL-PRCTR
                IMPORTING OUTPUT = PLANTDATA-PROFIT_CTR.
              PLANTDATAX-PROFIT_CTR = 'X'.
            ENDIF.
          ENDIF.

          IF WA_MASTER_UPL-MAGRV IS NOT INITIAL.
            CLIENTDATA-MAT_GRP_SM  = WA_MASTER_UPL-MAGRV.
            CLIENTDATAX-MAT_GRP_SM = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-TRAGR IS NOT INITIAL.
            CLIENTDATA-TRANS_GRP  = WA_MASTER_UPL-TRAGR.
            CLIENTDATAX-TRANS_GRP = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-XCHPF IS NOT INITIAL.
            HEADDATA-SALES_VIEW      = 'X'.
            PLANTDATA-BATCH_MGMT     = WA_MASTER_UPL-XCHPF.
            PLANTDATAX-BATCH_MGMT    = 'X'.
            CLIENTDATA-BATCH_MGMT    = WA_MASTER_UPL-XCHPF.
            CLIENTDATAX-BATCH_MGMT   = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-FERTH IS NOT INITIAL.
            CLIENTDATA-BASIC_MATL  = WA_MASTER_UPL-FERTH.
            CLIENTDATAX-BASIC_MATL = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-ZEINR IS NOT INITIAL.
            CLIENTDATA-DOCUMENT  = WA_MASTER_UPL-ZEINR.
            CLIENTDATAX-DOCUMENT = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-NORMT IS NOT INITIAL.
            CLIENTDATA-STD_DESCR  = WA_MASTER_UPL-NORMT.
            CLIENTDATAX-STD_DESCR = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-VHART IS NOT INITIAL.
            CLIENTDATA-SH_MAT_TYP  = WA_MASTER_UPL-VHART.
            CLIENTDATAX-SH_MAT_TYP = 'X'.
          ENDIF.

          IF WA_MASTER_UPL-VKORG IS NOT INITIAL
          AND WA_MASTER_UPL-VTWEG IS NOT INITIAL.
            HEADDATA-SALES_VIEW      = 'X'.
            SALESDATA-SALES_ORG      = WA_MASTER_UPL-VKORG.
            SALESDATAX-SALES_ORG     = WA_MASTER_UPL-VKORG.
            SALESDATA-DISTR_CHAN     = WA_MASTER_UPL-VTWEG.
            SALESDATAX-DISTR_CHAN    = WA_MASTER_UPL-VTWEG.
            IF WA_MASTER_UPL-DWERK IS NOT INITIAL.
              SALESDATA-DELYG_PLNT  = WA_MASTER_UPL-DWERK.
              SALESDATAX-DELYG_PLNT = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-VRKME IS NOT INITIAL.
              CALL FUNCTION 'CONVERSION_EXIT_CUNIT_INPUT'
                EXPORTING INPUT          = WA_MASTER_UPL-VRKME
                IMPORTING OUTPUT         = SALESDATA-SALES_UNIT
                EXCEPTIONS UNIT_NOT_FOUND = 1 OTHERS = 2.
              SALESDATAX-SALES_UNIT     = 'X'.
              SALESDATA-SALES_UNIT_ISO  = WA_MASTER_UPL-VRKME.
              SALESDATAX-SALES_UNIT_ISO = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-MTPOS  IS NOT INITIAL.
              SALESDATA-ITEM_CAT  = WA_MASTER_UPL-MTPOS.
              SALESDATAX-ITEM_CAT = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-KTGRM IS NOT INITIAL.
              SALESDATA-ACCT_ASSGT  = WA_MASTER_UPL-KTGRM.
              SALESDATAX-ACCT_ASSGT = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-MVGR1 IS NOT INITIAL.
              SALESDATA-MATL_GRP_1  = WA_MASTER_UPL-MVGR1.
              SALESDATAX-MATL_GRP_1 = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-MVGR2 IS NOT INITIAL.
              SALESDATA-MATL_GRP_2  = WA_MASTER_UPL-MVGR2.
              SALESDATAX-MATL_GRP_2 = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-MVGR3 IS NOT INITIAL.
              SALESDATA-MATL_GRP_4  = WA_MASTER_UPL-MVGR3.
              SALESDATAX-MATL_GRP_3 = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-MVGR4 IS NOT INITIAL.
              SALESDATA-MATL_GRP_4  = WA_MASTER_UPL-MVGR4.
              SALESDATAX-MATL_GRP_4 = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-MVGR5 IS NOT INITIAL.
              SALESDATA-MATL_GRP_5  = WA_MASTER_UPL-MVGR5.
              SALESDATAX-MATL_GRP_5 = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-HERKL IS NOT INITIAL.
              PLANTDATA-COUNTRYORI      = WA_MASTER_UPL-HERKL.
              PLANTDATA-COUNTRYORI_ISO  = WA_MASTER_UPL-HERKL.
              PLANTDATAX-COUNTRYORI     = 'X'.
              PLANTDATAX-COUNTRYORI_ISO = 'X'.
              WA_TAXCLASSIFICATIONS-DEPCOUNTRY     = WA_MASTER_UPL-HERKL.
              WA_TAXCLASSIFICATIONS-DEPCOUNTRY_ISO = WA_MASTER_UPL-HERKL.
            ENDIF.
            IF WA_MASTER_UPL-TAXM1 IS NOT INITIAL
            AND WA_MASTER_UPL-TATY1 IS NOT INITIAL.
              WA_TAXCLASSIFICATIONS-TAX_TYPE_1 = WA_MASTER_UPL-TATY1.
              WA_TAXCLASSIFICATIONS-TAXCLASS_1 = WA_MASTER_UPL-TAXM1.
              APPEND WA_TAXCLASSIFICATIONS TO TAXCLASSIFICATIONS.
            ENDIF.
            IF WA_MASTER_UPL-LADGR IS NOT INITIAL.
              PLANTDATA-LOADINGGRP  = WA_MASTER_UPL-LADGR.
              PLANTDATAX-LOADINGGRP = 'X'.
            ENDIF.
          ENDIF.

          IF WA_MASTER_UPL-WERKS IS NOT INITIAL.
*           MRP 1
            IF WA_MASTER_UPL-DISMM IS NOT INITIAL.
              HEADDATA-MRP_VIEW    = 'X'.
              PLANTDATA-MRP_TYPE   = WA_MASTER_UPL-DISMM.
              PLANTDATAX-MRP_TYPE  = 'X'.
              IF WA_MASTER_UPL-DISGR IS NOT INITIAL.
                PLANTDATA-MRP_GROUP  = WA_MASTER_UPL-DISGR.
                PLANTDATAX-MRP_GROUP = 'X'.
              ENDIF.
              IF WA_MASTER_UPL-DISPO IS NOT INITIAL.
                PLANTDATA-MRP_CTRLER  = WA_MASTER_UPL-DISPO.
                PLANTDATAX-MRP_CTRLER = 'X'.
              ENDIF.
              IF WA_MASTER_UPL-DISLS IS NOT INITIAL.
                PLANTDATA-LOTSIZEKEY  = WA_MASTER_UPL-DISLS.
                PLANTDATAX-LOTSIZEKEY = 'X'.
              ENDIF.
              IF WA_MASTER_UPL-BSTMI IS NOT INITIAL.
                PLANTDATA-MINLOTSIZE  = WA_MASTER_UPL-BSTMI.
                PLANTDATAX-MINLOTSIZE = 'X'.
              ENDIF.
              IF WA_MASTER_UPL-BSTMA IS NOT INITIAL.
                PLANTDATA-MAXLOTSIZE  = WA_MASTER_UPL-BSTMA.
                PLANTDATAX-MAXLOTSIZE = 'X'.
              ENDIF.
              IF WA_MASTER_UPL-BSTRF IS NOT INITIAL.
                PLANTDATA-ROUND_VAL  = WA_MASTER_UPL-BSTRF.
                PLANTDATAX-ROUND_VAL = 'X'.
              ENDIF.
              IF WA_MASTER_UPL-MMSTA IS NOT INITIAL.
                PLANTDATA-PUR_STATUS  = WA_MASTER_UPL-MMSTA.
                PLANTDATAX-PUR_STATUS = 'X'.
              ENDIF.
            ENDIF.
*           MRP 2
            IF WA_MASTER_UPL-BESKZ IS NOT INITIAL.
              HEADDATA-MRP_VIEW     = 'X'.
              PLANTDATA-PROC_TYPE   = WA_MASTER_UPL-BESKZ.
              PLANTDATAX-PROC_TYPE  = 'X'.
              IF WA_MASTER_UPL-SOBSL IS NOT INITIAL.
                PLANTDATA-SPPROCTYPE  = WA_MASTER_UPL-SOBSL.
                PLANTDATAX-SPPROCTYPE = 'X'.
              ENDIF.
              IF WA_MASTER_UPL-RGEKZ IS NOT INITIAL.
                PLANTDATA-BACKFLUSH  = WA_MASTER_UPL-RGEKZ.
                PLANTDATAX-BACKFLUSH = 'X'.
              ENDIF.
              IF WA_MASTER_UPL-DZEIT IS NOT INITIAL.
                PLANTDATA-INHSEPRODT  = WA_MASTER_UPL-DZEIT.
                PLANTDATAX-INHSEPRODT = 'X'.
              ENDIF.
              IF WA_MASTER_UPL-WEBAZ IS NOT INITIAL.
                PLANTDATA-GR_PR_TIME  = WA_MASTER_UPL-WEBAZ.
                PLANTDATAX-GR_PR_TIME = 'X'.
              ENDIF.
              IF WA_MASTER_UPL-FHORI IS NOT INITIAL.
                PLANTDATA-SM_KEY  = WA_MASTER_UPL-FHORI.
                PLANTDATAX-SM_KEY = 'X'.
              ENDIF.
              IF WA_MASTER_UPL-EISBE IS NOT INITIAL.
                PLANTDATA-SAFETY_STK  = WA_MASTER_UPL-EISBE.
                PLANTDATAX-SAFETY_STK = 'X'.
              ENDIF.
            ENDIF.
*           MRP 3
            IF WA_MASTER_UPL-MTVFP IS NOT INITIAL.
              HEADDATA-MRP_VIEW      = 'X'.
              PLANTDATA-AVAILCHECK   = WA_MASTER_UPL-MTVFP.
              PLANTDATAX-AVAILCHECK  = 'X'.
              IF WA_MASTER_UPL-STRGR IS NOT INITIAL.
                PLANTDATA-PLAN_STRGP  = WA_MASTER_UPL-STRGR.
                PLANTDATAX-PLAN_STRGP = 'X'.
              ENDIF.
              IF WA_MASTER_UPL-VRMOD IS NOT INITIAL.
                PLANTDATA-CONSUMMODE  = WA_MASTER_UPL-VRMOD.
                PLANTDATAX-CONSUMMODE = 'X'.
              ENDIF.
              IF WA_MASTER_UPL-VINT2 IS NOT INITIAL.
                PLANTDATA-FWD_CONS  = WA_MASTER_UPL-VINT2.
                PLANTDATAX-FWD_CONS = 'X'.
              ENDIF.
              IF WA_MASTER_UPL-VINT1 IS NOT INITIAL.
                PLANTDATA-BWD_CONS  = WA_MASTER_UPL-VINT1.
                PLANTDATAX-BWD_CONS = 'X'.
              ENDIF.
              IF WA_MASTER_UPL-PERIV IS NOT INITIAL.
                PLANTDATA-FY_VARIANT  = WA_MASTER_UPL-PERIV.
                PLANTDATAX-FY_VARIANT = 'X'.
              ENDIF.
              IF WA_MASTER_UPL-PERKZ IS NOT INITIAL.
                PLANTDATA-PERIOD_IND  = WA_MASTER_UPL-PERKZ.
                PLANTDATAX-PERIOD_IND = 'X'.
              ENDIF.
            ENDIF.
*           MRP 4
            IF WA_MASTER_UPL-ALTSL IS NOT INITIAL
            OR WA_MASTER_UPL-SBDKZ IS NOT INITIAL.
              HEADDATA-MRP_VIEW     = 'X'.
              PLANTDATA-ALT_BOM_ID  = WA_MASTER_UPL-ALTSL.
              PLANTDATAX-ALT_BOM_ID = 'X'.
              PLANTDATA-DEP_REQ_ID  = WA_MASTER_UPL-SBDKZ.
              PLANTDATAX-DEP_REQ_ID = 'X'.
            ENDIF.
          ENDIF.

*         ACCOUNTING 1
          IF WA_MASTER_UPL-WERKS IS NOT INITIAL.
            HEADDATA-ACCOUNT_VIEW   = 'X'.
            VALUATIONDATA-VAL_AREA  = WA_MASTER_UPL-WERKS.
            VALUATIONDATAX-VAL_AREA = WA_MASTER_UPL-WERKS.
            IF WA_MASTER_UPL-BKLAS IS NOT INITIAL.
              VALUATIONDATA-VAL_CLASS  = WA_MASTER_UPL-BKLAS.
              VALUATIONDATAX-VAL_CLASS = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-STPRS IS NOT INITIAL.
              VALUATIONDATA-STD_PRICE  = WA_MASTER_UPL-STPRS.
              VALUATIONDATAX-STD_PRICE = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-VERPR IS NOT INITIAL.
              VALUATIONDATA-MOVING_PR  = WA_MASTER_UPL-VERPR.
              VALUATIONDATAX-MOVING_PR = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-PEINH IS NOT INITIAL.
              VALUATIONDATA-PRICE_UNIT  = WA_MASTER_UPL-PEINH.
              VALUATIONDATAX-PRICE_UNIT = 'X'.
            ENDIF.
            IF WA_MASTER_UPL-VPRSV IS NOT INITIAL.
              VALUATIONDATA-PRICE_CTRL  = WA_MASTER_UPL-VPRSV.
              VALUATIONDATAX-PRICE_CTRL = 'X'.
            ENDIF.
          ENDIF.

*         WORK SCHEDULING
          HEADDATA-WORK_SCHED_VIEW = 'X'.
          IF WA_MASTER_UPL-AUSME IS NOT INITIAL.
            CALL FUNCTION 'CONVERSION_EXIT_CUNIT_INPUT'
              EXPORTING INPUT          = WA_MASTER_UPL-AUSME
              IMPORTING OUTPUT         = PLANTDATA-ISSUE_UNIT
              EXCEPTIONS UNIT_NOT_FOUND = 1 OTHERS = 2.
            PLANTDATA-ISSUE_UNIT_ISO  = PLANTDATA-ISSUE_UNIT.
            PLANTDATAX-ISSUE_UNIT     = 'X'.
            PLANTDATAX-ISSUE_UNIT_ISO = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-LGPRO IS NOT INITIAL.
            PLANTDATA-ISS_ST_LOC  = WA_MASTER_UPL-LGPRO.
            PLANTDATAX-ISS_ST_LOC = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-SFCPF IS NOT INITIAL.
            PLANTDATA-PRODPROF  = WA_MASTER_UPL-SFCPF.
            PLANTDATAX-PRODPROF = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-UNETO IS NOT INITIAL.
            PLANTDATA-UNDER_TOL  = WA_MASTER_UPL-UNETO.
            PLANTDATAX-UNDER_TOL = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-UEETO IS NOT INITIAL.
            PLANTDATA-OVER_TOL  = WA_MASTER_UPL-UEETO.
            PLANTDATAX-OVER_TOL = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-UEETK IS NOT INITIAL.
            PLANTDATA-UNLIMITED  = WA_MASTER_UPL-UEETK.
            PLANTDATAX-UNLIMITED = 'X'.
          ENDIF.

*           IF WA_MASTER_UPL-SERNP IS NOT INITIAL.
*            PLANTDATA-SERNO_PROF  = WA_MASTER_UPL-SERNP.
*            PLANTDATAX-SERNO_PROF = 'X'.
*           ENDIF.

*         COSTING 1
          IF WA_MASTER_UPL-EKALR IS NOT INITIAL
          OR WA_MASTER_UPL-LOSGR IS NOT INITIAL.
            HEADDATA-COST_VIEW        = 'X'.
            VALUATIONDATA-QTY_STRUCT  = WA_MASTER_UPL-EKALR.
            VALUATIONDATAX-QTY_STRUCT = 'X'.
            PLANTDATA-LOT_SIZE        = WA_MASTER_UPL-LOSGR.
            PLANTDATAX-LOT_SIZE       = 'X'.
          ENDIF.

          IF WA_MASTER_UPL-LGFSB IS NOT INITIAL.
            PLANTDATA-SLOC_EXPRC  = WA_MASTER_UPL-LGFSB.
            PLANTDATAX-SLOC_EXPRC = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-EKGRP IS NOT INITIAL.
            PLANTDATA-PUR_GROUP  = WA_MASTER_UPL-EKGRP.
            PLANTDATAX-PUR_GROUP = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-HKMAT IS NOT INITIAL.
            VALUATIONDATA-ORIG_MAT  = WA_MASTER_UPL-HKMAT.
            VALUATIONDATAX-ORIG_MAT = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-PLIFZ IS NOT INITIAL.
            PLANTDATA-PLND_DELRY  = WA_MASTER_UPL-PLIFZ.
            PLANTDATAX-PLND_DELRY = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-NCOST IS NOT INITIAL.
            PLANTDATA-NO_COSTING  = WA_MASTER_UPL-NCOST.
            PLANTDATAX-NO_COSTING = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-EPRIO IS NOT INITIAL.
            PLANTDATA-DETERM_GRP  = WA_MASTER_UPL-EPRIO.
            PLANTDATAX-DETERM_GRP = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-EXTWG IS NOT INITIAL.
            CLIENTDATA-EXTMATLGRP  = WA_MASTER_UPL-EXTWG.
            CLIENTDATAX-EXTMATLGRP = 'X'.
          ENDIF.
          IF WA_MASTER_UPL-INSPTYPE IS NOT INITIAL.
            HEADDATA-QUALITY_VIEW = 'X'.
          ENDIF.

          CALL FUNCTION 'BAPI_MATERIAL_SAVEDATA'
            EXPORTING
              HEADDATA             = HEADDATA
              CLIENTDATA           = CLIENTDATA
              CLIENTDATAX          = CLIENTDATAX
              PLANTDATA            = PLANTDATA
              PLANTDATAX           = PLANTDATAX
              STORAGELOCATIONDATA  = STORAGELOCATIONDATA
              STORAGELOCATIONDATAX = STORAGELOCATIONDATAX
              VALUATIONDATA        = VALUATIONDATA
              VALUATIONDATAX       = VALUATIONDATAX
              SALESDATA            = SALESDATA
              SALESDATAX           = SALESDATAX
            IMPORTING
              RETURN               = RETURN
            TABLES
              MATERIALDESCRIPTION  = MATERIALDESCRIPTION
              UNITSOFMEASURE       = UNITSOFMEASURE
              UNITSOFMEASUREX      = UNITSOFMEASUREX
              TAXCLASSIFICATIONS   = TAXCLASSIFICATIONS
              RETURNMESSAGES       = RETURNMES.

          IF RETURN-TYPE = 'E'.
            CLEAR WMESSAGE.
            LOOP AT RETURNMES INTO WA_RETURNMES WHERE TYPE EQ 'E'.
              CONCATENATE WMESSAGE WA_RETURNMES-MESSAGE
                INTO WMESSAGE SEPARATED BY SPACE.
              CONDENSE WMESSAGE.
            ENDLOOP.
            MOVE-CORRESPONDING WA_MASTER_UPL TO WA_ERR_TAB.
            WA_ERR_TAB-ZERR_LOG = WMESSAGE.
            APPEND WA_ERR_TAB TO ERR_TAB.
            CLEAR  WA_ERR_TAB.
          ELSE.
            CALL FUNCTION 'DEQUEUE_ALL'.

*           Quality Management
            IF WA_MASTER_UPL-INSPTYPE IS NOT INITIAL
            AND WA_MASTER_UPL-IND_INSPTYPE_MAT_ACTIVE IS NOT INITIAL.
              REFRESH: INSPECTIONCTRL, RETURN_QM.
              CLEAR  : GW_INSPECTIONCTRL, GW_RETURN_QM, XCONCAT_ERR.
              GW_INSPECTIONCTRL-INSPTYPE                  = WA_MASTER_UPL-INSPTYPE.
              GW_INSPECTIONCTRL-MATERIAL                  = WA_MASTER_UPL-MATNR.
              GW_INSPECTIONCTRL-PLANT                     = WA_MASTER_UPL-WERKS.
              GW_INSPECTIONCTRL-IND_INSP_WITH_TSK_LIST    = WA_MASTER_UPL-IND_INSP_WITH_TSK_LIST.
              GW_INSPECTIONCTRL-IND_SPEC_MATSPEC          = WA_MASTER_UPL-IND_SPEC_MATSPEC.
              GW_INSPECTIONCTRL-IND_SPEC_CONFIG           = WA_MASTER_UPL-IND_SPEC_CONFIG.
              GW_INSPECTIONCTRL-IND_SPEC_BATCH            = WA_MASTER_UPL-IND_SPEC_BATCH.
              GW_INSPECTIONCTRL-IND_AUTO_ASSIGN           = WA_MASTER_UPL-IND_AUTO_ASSIGN.
              GW_INSPECTIONCTRL-IND_INSP_BY_CHARAC        = WA_MASTER_UPL-IND_INSP_BY_CHARAC.
              GW_INSPECTIONCTRL-IND_POST_TO_INSP_STOCK    = WA_MASTER_UPL-IND_POST_TO_INSP_STOCK.
              GW_INSPECTIONCTRL-IND_AUTOMATIC_UD          = WA_MASTER_UPL-IND_AUTOMATIC_UD.
              GW_INSPECTIONCTRL-SAMPLING_PROCEDURE        = WA_MASTER_UPL-SAMPLING_PROCEDURE.
              GW_INSPECTIONCTRL-DYN_MODIF_RULE            = WA_MASTER_UPL-DYN_MODIF_RULE.
              GW_INSPECTIONCTRL-INSP_PERCENTAGE           = WA_MASTER_UPL-INSP_PERCENTAGE.
              GW_INSPECTIONCTRL-IND_100_PERCENT_INSPECTION = WA_MASTER_UPL-IND_100_PERCENT_INSPECTION.
              GW_INSPECTIONCTRL-IND_SKIPS_ALLOWED         = WA_MASTER_UPL-IND_SKIPS_ALLOWED.
              GW_INSPECTIONCTRL-IND_MANUAL_SAMPLE         = WA_MASTER_UPL-IND_MANUAL_SAMPLE.
              GW_INSPECTIONCTRL-IND_MANUAL_SAMPLE_CALC    = WA_MASTER_UPL-IND_MANUAL_SAMPLE_CALC.
              GW_INSPECTIONCTRL-IND_SINGLE_UNITS_POSSIBLE = WA_MASTER_UPL-IND_SINGLE_UNITS_POSSIBLE.
              GW_INSPECTIONCTRL-AVE_INSP_DURATION         = WA_MASTER_UPL-AVE_INSP_DURATION.
              GW_INSPECTIONCTRL-CONTR_INSP_LOT_CREATE     = WA_MASTER_UPL-CONTR_INSP_LOT_CREATE.
              GW_INSPECTIONCTRL-QUAL_SCORE_PROCEDURE      = WA_MASTER_UPL-QUAL_SCORE_PROCEDURE.
              GW_INSPECTIONCTRL-ALLOWED_SCRAP_SHARE       = WA_MASTER_UPL-ALLOWED_SCRAP_SHARE.
              GW_INSPECTIONCTRL-IND_SPECIAL_QM_ORDER      = WA_MASTER_UPL-IND_SPECIAL_QM_ORDER.
              GW_INSPECTIONCTRL-QM_ORDERID                = WA_MASTER_UPL-QM_ORDERID.
              GW_INSPECTIONCTRL-IND_INSPTYPE_MAT_ACTIVE   = WA_MASTER_UPL-IND_INSPTYPE_MAT_ACTIVE.
              GW_INSPECTIONCTRL-PREFERRED_INSPTYPE        = WA_MASTER_UPL-PREFERRED_INSPTYPE.
              GW_INSPECTIONCTRL-INSPTYPE_DELETE           = WA_MASTER_UPL-INSPTYPE_DELETE.
              GW_INSPECTIONCTRL-MATERIAL_EXTERNAL         = WA_MASTER_UPL-MATERIAL_EXTERNAL.
              GW_INSPECTIONCTRL-MATERIAL_GUID             = WA_MASTER_UPL-MATERIAL_GUID.
              GW_INSPECTIONCTRL-MATERIAL_VERSION          = WA_MASTER_UPL-MATERIAL_VERSION.
              GW_INSPECTIONCTRL-IND_HU_INSPECTION         = WA_MASTER_UPL-IND_HU_INSPECTION.
              GW_INSPECTIONCTRL-MS_FLAG                   = WA_MASTER_UPL-MS_FLAG.
              APPEND GW_INSPECTIONCTRL TO INSPECTIONCTRL.
              CLEAR  GW_INSPECTIONCTRL.

              CALL FUNCTION 'BAPI_MATINSPCTRL_SAVEREPLICA'
                TABLES RETURN         = RETURN_QM
                       INSPECTIONCTRL = INSPECTIONCTRL.

              IF RETURN_QM[] IS INITIAL.
                CALL FUNCTION 'BAPI_TRANSACTION_COMMIT' EXPORTING WAIT = 'X'.
              ELSE.
                CLEAR: WA_ERR_TAB, XCONCAT_ERR.
                LOOP AT RETURN_QM INTO GW_RETURN_QM.
                  CONCATENATE GW_RETURN_QM-MESSAGE GW_RETURN_QM-MESSAGE_V1
                    GW_RETURN_QM-MESSAGE_V2 INTO XCONCAT_ERR SEPARATED BY ' '.
                  WA_ERR_TAB-MATNR    = WA_MASTER_UPL-MATNR.
                  WA_ERR_TAB-ZERR_LOG = XCONCAT_ERR.
                  APPEND WA_ERR_TAB TO ERR_TAB.
                  CLEAR WA_ERR_TAB.
                  EXIT.
                ENDLOOP.
              ENDIF.
            ENDIF.

*           CLASSIFICATION
            CHECK WA_MASTER_UPL-CLASS IS NOT INITIAL
               OR ( WA_MASTER_UPL-WARNA IS NOT INITIAL
               AND  WA_MASTER_UPL-VOL_PROD IS NOT INITIAL ).

            REFRESH: I_BAPI_NUM, I_OBJ_DETAIL, I_BAPI_CURR, I_CLASS, I_OBJECTDATA.
            CLEAR  : I_BAPI_NUM, I_OBJ_DETAIL, I_BAPI_CURR, XBAPI_OBJECT,
                     XCLASS_NUM, XCLASS_TYP, WA_CLASS, WA_OBJECTDATA.
            XBAPI_OBJECT = HEADDATA-MATERIAL_LONG.

            IF WA_MASTER_UPL-CLASS IS NOT INITIAL.
              IF WA_MASTER_UPL-CLASS EQ 'WARNA'.
                XCLASS_TYP = '001'.
              ELSE.
                XCLASS_TYP = '023'.
              ENDIF.
              XCLASS_NUM = WA_MASTER_UPL-CLASS.

              CLEAR XCONCAT_ERR.
              CALL FUNCTION 'BAPI_OBJCL_CHANGE'
                EXPORTING
                  OBJECTKEY          = XBAPI_OBJECT
                  OBJECTTABLE        = 'MARA'
                  CLASSNUM           = XCLASS_NUM
                  CLASSTYPE          = XCLASS_TYP
                  STATUS             = '1'
                TABLES
                  ALLOCVALUESNUMNEW  = I_BAPI_NUM
                  ALLOCVALUESCHARNEW = I_OBJ_DETAIL
                  ALLOCVALUESCURRNEW = I_BAPI_CURR
                  RETURN             = I_RETURN2.

              LOOP AT I_RETURN2 INTO WA_RETURN2 WHERE TYPE EQ 'E'.
                XERR_INDI = 'X'.
                IF WA_RETURN2-MESSAGE IS NOT INITIAL.
                  XERR_MESSAGE = WA_RETURN2-MESSAGE.
                ELSE.
                  SELECT SINGLE * FROM T100 INTO CORRESPONDING FIELDS OF WA_T100
                    WHERE SPRSL EQ SY-LANGU AND ARBGB EQ WA_RETURN2-ID
                      AND MSGNR EQ WA_RETURN2-NUMBER.
                  IF SY-SUBRC = 0.
                    CONCATENATE XERR_MESSAGE WA_T100-TEXT INTO XERR_MESSAGE.
                    IF XERR_MESSAGE CS '&1'.
                      REPLACE ALL OCCURRENCES OF '&1' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V1.
                      REPLACE ALL OCCURRENCES OF '&2' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V2.
                      REPLACE ALL OCCURRENCES OF '&3' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V3.
                      REPLACE ALL OCCURRENCES OF '&4' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V4.
                    ELSE.
                      REPLACE FIRST OCCURRENCE OF '&' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V1.
                      REPLACE FIRST OCCURRENCE OF '&' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V2.
                      REPLACE FIRST OCCURRENCE OF '&' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V3.
                      REPLACE FIRST OCCURRENCE OF '&' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V4.
                    ENDIF.
                    CONDENSE XERR_MESSAGE.
                  ENDIF.
                ENDIF.
                IF XCONCAT_ERR IS INITIAL.
                  XCONCAT_ERR = XERR_MESSAGE.
                ELSE.
                  CONCATENATE XCONCAT_ERR XERR_MESSAGE INTO XCONCAT_ERR SEPARATED BY SPACE.
                ENDIF.
              ENDLOOP.

              IF XERR_INDI IS NOT INITIAL.
                WA_ERR_TAB-MATNR    = WA_MASTER_UPL-MATNR.
                WA_ERR_TAB-ZERR_LOG = XCONCAT_ERR.
                APPEND WA_ERR_TAB TO ERR_TAB.
                CLEAR WA_ERR_TAB.
                EXIT.
              ENDIF.
              CLEAR WA_RETURN.
              CALL FUNCTION 'BAPI_TRANSACTION_COMMIT' EXPORTING WAIT = 'X'.
            ENDIF.

            IF WA_MASTER_UPL-WARNA IS NOT INITIAL
            AND WA_MASTER_UPL-VOL_PROD IS NOT INITIAL
            AND XERR_INDI IS INITIAL.
              REFRESH: I_BAPI_NUM, I_OBJ_DETAIL, I_BAPI_CURR, I_CLASS, I_OBJECTDATA.
              CLEAR  : I_BAPI_NUM, I_OBJ_DETAIL, I_BAPI_CURR, XCLASS_NUM, XCLASS_TYP,
                       WA_CLASS, WA_OBJECTDATA.
              XCLASS_TYP = '001'.
              WA_CLASS-KLART = '001'. WA_CLASS-CLASS = 'WARNA'.
              APPEND WA_CLASS TO I_CLASS. CLEAR WA_CLASS.
              WA_CLASS-KLART = '001'. WA_CLASS-CLASS = 'DIMENSI'.
              APPEND WA_CLASS TO I_CLASS. CLEAR WA_CLASS.
              WA_OBJECTDATA-TABIX = 1. WA_OBJECTDATA-ATNAM = 'WARNA'.
              APPEND WA_OBJECTDATA TO I_OBJECTDATA. CLEAR WA_CLASS.
              WA_OBJECTDATA-TABIX = 2. WA_OBJECTDATA-ATNAM = 'VOLUME_PRODUCT'.
              APPEND WA_OBJECTDATA TO I_OBJECTDATA. CLEAR WA_OBJECTDATA.

              LOOP AT I_CLASS INTO WA_CLASS.
                XCLASS_NUM = WA_CLASS-CLASS.
                XTABIX = SY-TABIX.
                LOOP AT I_OBJECTDATA INTO WA_OBJECTDATA
                  WHERE TABIX EQ XTABIX
                    AND ( ATNAM EQ 'WARNA' OR ATNAM EQ 'VOLUME_PRODUCT' ).
                  CLEAR WA_OBJ_DETAIL.
                  WA_OBJ_DETAIL-CHARACT = WA_OBJECTDATA-ATNAM.
                  CASE WA_OBJECTDATA-ATNAM.
                    WHEN 'WARNA'.        WA_OBJ_DETAIL-VALUE_CHAR = WA_MASTER_UPL-WARNA.
                    WHEN 'VOLUME_PRODUCT'. WA_OBJ_DETAIL-VALUE_CHAR = WA_MASTER_UPL-VOL_PROD.
                  ENDCASE.
                  WA_OBJ_DETAIL-INHERITED    = WA_OBJECTDATA-INHER.
                  WA_OBJ_DETAIL-INSTANCE     = WA_OBJECTDATA-ATZIS.
                  WA_OBJ_DETAIL-CHARACT_DESCR = WA_OBJECTDATA-SMBEZ.
                  READ TABLE I_OBJ_DETAIL TRANSPORTING NO FIELDS
                    WITH KEY CHARACT = WA_OBJECTDATA-ATNAM.
                  IF SY-SUBRC EQ 0.
                    MODIFY I_OBJ_DETAIL FROM WA_OBJ_DETAIL INDEX SY-TABIX.
                  ELSE.
                    APPEND WA_OBJ_DETAIL TO I_OBJ_DETAIL.
                  ENDIF.
                ENDLOOP.

                CLEAR XCONCAT_ERR.
                CALL FUNCTION 'BAPI_OBJCL_CHANGE'
                  EXPORTING
                    OBJECTKEY          = XBAPI_OBJECT
                    OBJECTTABLE        = 'MARA'
                    CLASSNUM           = XCLASS_NUM
                    CLASSTYPE          = XCLASS_TYP
                    STATUS             = '1'
                  TABLES
                    ALLOCVALUESNUMNEW  = I_BAPI_NUM
                    ALLOCVALUESCHARNEW = I_OBJ_DETAIL
                    ALLOCVALUESCURRNEW = I_BAPI_CURR
                    RETURN             = I_RETURN2.

                LOOP AT I_RETURN2 INTO WA_RETURN2 WHERE TYPE EQ 'E'.
                  XERR_INDI = 'X'.
                  IF WA_RETURN2-MESSAGE IS NOT INITIAL.
                    XERR_MESSAGE = WA_RETURN2-MESSAGE.
                  ELSE.
                    SELECT SINGLE * FROM T100 INTO CORRESPONDING FIELDS OF WA_T100
                      WHERE SPRSL EQ SY-LANGU AND ARBGB EQ WA_RETURN2-ID
                        AND MSGNR EQ WA_RETURN2-NUMBER.
                    IF SY-SUBRC = 0.
                      CONCATENATE XERR_MESSAGE WA_T100-TEXT INTO XERR_MESSAGE.
                      IF XERR_MESSAGE CS '&1'.
                        REPLACE ALL OCCURRENCES OF '&1' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V1.
                        REPLACE ALL OCCURRENCES OF '&2' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V2.
                        REPLACE ALL OCCURRENCES OF '&3' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V3.
                        REPLACE ALL OCCURRENCES OF '&4' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V4.
                      ELSE.
                        REPLACE FIRST OCCURRENCE OF '&' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V1.
                        REPLACE FIRST OCCURRENCE OF '&' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V2.
                        REPLACE FIRST OCCURRENCE OF '&' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V3.
                        REPLACE FIRST OCCURRENCE OF '&' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V4.
                      ENDIF.
                      CONDENSE XERR_MESSAGE.
                    ENDIF.
                  ENDIF.
                  IF XCONCAT_ERR IS INITIAL.
                    XCONCAT_ERR = XERR_MESSAGE.
                  ELSE.
                    CONCATENATE XCONCAT_ERR XERR_MESSAGE INTO XCONCAT_ERR SEPARATED BY SPACE.
                  ENDIF.
                ENDLOOP.

                IF XERR_INDI IS NOT INITIAL.
                  CLEAR WA_ERR_TAB.
                  WA_ERR_TAB-MATNR    = WA_MASTER_UPL-MATNR.
                  WA_ERR_TAB-ZERR_LOG = XCONCAT_ERR.
                  APPEND WA_ERR_TAB TO ERR_TAB.
                  EXIT.
                ELSE.
                  CLEAR WA_RETURN.
                  CALL FUNCTION 'BAPI_TRANSACTION_COMMIT' EXPORTING WAIT = 'X'.
                ENDIF.
              ENDLOOP.
            ENDIF.

*           PRODUCT UNITS CHARACTERISTIC
            IF XERR_INDI IS NOT INITIAL
            AND WA_MASTER_UPL-KZWSM IS NOT INITIAL
            AND WA_MASTER_UPL-CLASS IS NOT INITIAL.
              READ TABLE I_KLAH INTO WA_KLAH WITH KEY CLASS = WA_MASTER_UPL-CLASS.
              IF SY-SUBRC EQ 0.
                READ TABLE I_KSML INTO WA_KSML WITH KEY CLINT = WA_KLAH-CLINT.
                IF SY-SUBRC EQ 0.
                  READ TABLE I_CABN INTO WA_CABN WITH KEY ATINN = WA_KSML-IMERK.
                  IF SY-SUBRC EQ 0.
                    MATERIALDATA-UOMUSAGE  = WA_MASTER_UPL-KZWSM.
                    MATERIALDATAX-UOMUSAGE = 'X'.
                    COMPLETEREPLICATION    = 'X'.
                    WA_BATCHSPECIFICUOM-BATCHSPECIFICUOM     = 'ST'.
                    WA_BATCHSPECIFICUOM-BATCHSPECIFICUOM_ISO = 'ST'.
                    WA_BATCHSPECIFICUOM-NAME_CHAR            = WA_CABN-ATNAM.
                    WA_BATCHSPECIFICUOM-PLANNEDVALUE         = 1.
                    APPEND WA_BATCHSPECIFICUOM  TO BATCHSPECIFICUOM.
                    CLEAR  WA_BATCHSPECIFICUOM.
                    WA_BATCHSPECIFICUOMX-BATCHSPECIFICUOM     = 'ST'.
                    WA_BATCHSPECIFICUOMX-BATCHSPECIFICUOM_ISO = 'ST'.
                    WA_BATCHSPECIFICUOMX-NAME_CHAR            = 'X'.
                    WA_BATCHSPECIFICUOMX-PLANNEDVALUE         = 'X'.
                    APPEND WA_BATCHSPECIFICUOMX TO BATCHSPECIFICUOMX.
                    CLEAR  WA_BATCHSPECIFICUOMX.
                    CLEAR: XERR_MESSAGE, XCONCAT_ERR.
                    CALL FUNCTION 'BAPI_BMUOM_SAVEREPLICAMULTIPLE'
                      EXPORTING
                        MATERIALNUMBER      = WA_MASTER_UPL-MATNR
                        MATERIALDATA        = MATERIALDATA
                        MATERIALDATAX       = MATERIALDATAX
                        COMPLETEREPLICATION = COMPLETEREPLICATION
                      TABLES
                        BATCHSPECIFICUOM    = BATCHSPECIFICUOM
                        BATCHSPECIFICUOMX   = BATCHSPECIFICUOMX
                        RETURN              = I_RETURN.
                    LOOP AT I_RETURN INTO WA_RETURN WHERE TYPE EQ 'E'.
                      XERR_INDI = 'X'.
                      IF WA_RETURN-MESSAGE IS NOT INITIAL.
                        XERR_MESSAGE = WA_RETURN-MESSAGE.
                      ELSE.
                        SELECT SINGLE * FROM T100 INTO CORRESPONDING FIELDS OF WA_T100
                          WHERE SPRSL EQ SY-LANGU AND ARBGB EQ WA_RETURN-ID
                            AND MSGNR EQ WA_RETURN-NUMBER.
                        IF SY-SUBRC = 0.
                          CONCATENATE XERR_MESSAGE WA_T100-TEXT INTO XERR_MESSAGE.
                          IF XERR_MESSAGE CS '&1'.
                            REPLACE ALL OCCURRENCES OF '&1' IN XERR_MESSAGE WITH WA_RETURN-MESSAGE_V1.
                            REPLACE ALL OCCURRENCES OF '&2' IN XERR_MESSAGE WITH WA_RETURN-MESSAGE_V2.
                            REPLACE ALL OCCURRENCES OF '&3' IN XERR_MESSAGE WITH WA_RETURN-MESSAGE_V3.
                            REPLACE ALL OCCURRENCES OF '&4' IN XERR_MESSAGE WITH WA_RETURN-MESSAGE_V4.
                          ELSE.
                            REPLACE FIRST OCCURRENCE OF '&' IN XERR_MESSAGE WITH WA_RETURN-MESSAGE_V1.
                            REPLACE FIRST OCCURRENCE OF '&' IN XERR_MESSAGE WITH WA_RETURN-MESSAGE_V2.
                            REPLACE FIRST OCCURRENCE OF '&' IN XERR_MESSAGE WITH WA_RETURN-MESSAGE_V3.
                            REPLACE FIRST OCCURRENCE OF '&' IN XERR_MESSAGE WITH WA_RETURN-MESSAGE_V4.
                          ENDIF.
                          CONDENSE XERR_MESSAGE.
                        ENDIF.
                      ENDIF.
                      IF XCONCAT_ERR IS INITIAL.
                        XCONCAT_ERR = XERR_MESSAGE.
                      ELSE.
                        CONCATENATE XCONCAT_ERR XERR_MESSAGE INTO XCONCAT_ERR SEPARATED BY SPACE.
                      ENDIF.
                    ENDLOOP.
                    IF XERR_INDI IS NOT INITIAL.
                      CLEAR WA_ERR_TAB.
                      WA_ERR_TAB-MATNR    = WA_MASTER_UPL-MATNR.
                      WA_ERR_TAB-ZERR_LOG = XCONCAT_ERR.
                      APPEND WA_ERR_TAB TO ERR_TAB.
                      CLEAR WA_ERR_TAB.
                      EXIT.
                    ELSE.
                      CLEAR WA_RETURN.
                      CALL FUNCTION 'BAPI_TRANSACTION_COMMIT' EXPORTING WAIT = 'X'.
                    ENDIF.
                  ENDIF.
                ENDIF.
              ENDIF.
            ENDIF.

*           ACCOUNTING TAB HARD CURRENCY
            IF WA_MASTER_UPL-WERKS IS NOT INITIAL
            AND WA_MASTER_UPL-PEINH_2 IS NOT INITIAL.
              REFRESH: I_PRICES, I_RETURN2.
              CLEAR  : WA_BAPI_MATVAL_KEY, WA_BAPI_MATVAL_PRICEDATE, WA_PRICES.
              CALL FUNCTION 'CONVERSION_EXIT_MATN1_INPUT'
                EXPORTING INPUT        = WA_MASTER_UPL-MATNR
                IMPORTING OUTPUT       = WA_BAPI_MATVAL_KEY-MATERIAL
                EXCEPTIONS LENGTH_ERROR = 1 OTHERS = 2.
              WA_BAPI_MATVAL_KEY-VAL_AREA  = WA_MASTER_UPL-WERKS.
              WA_PRICES-CURR_TYPE          = '40'.
              WA_PRICES-CURRENCY           = 'USD'.
              WA_PRICES-CURRENCY_ISO       = 'USD'.
              WA_PRICES-PRICE_UNIT         = WA_MASTER_UPL-PEINH_2.
              APPEND WA_PRICES TO I_PRICES. CLEAR WA_PRICES.
              CALL FUNCTION 'CKML_MATVAL_PRICE_CHANGE'
                EXPORTING
                  MATERIAL      = WA_BAPI_MATVAL_KEY-MATERIAL
                  VALUATIONAREA = WA_BAPI_MATVAL_KEY-VAL_AREA
                  VALUATIONTYPE = WA_BAPI_MATVAL_KEY-VAL_TYPE
                  PRICEDATE     = WA_BAPI_MATVAL_PRICEDATE
                TABLES
                  PRICES        = I_PRICES
                  RETURN        = I_RETURN2.
              LOOP AT I_RETURN2 INTO WA_RETURN2 WHERE TYPE EQ 'E'.
                XERR_INDI = 'X'.
                IF WA_RETURN2-MESSAGE IS NOT INITIAL.
                  XERR_MESSAGE = WA_RETURN2-MESSAGE.
                ELSE.
                  SELECT SINGLE * FROM T100 INTO CORRESPONDING FIELDS OF WA_T100
                    WHERE SPRSL EQ SY-LANGU AND ARBGB EQ WA_RETURN2-ID
                      AND MSGNR EQ WA_RETURN2-NUMBER.
                  IF SY-SUBRC = 0.
                    CONCATENATE XERR_MESSAGE WA_T100-TEXT INTO XERR_MESSAGE.
                    IF XERR_MESSAGE CS '&1'.
                      REPLACE ALL OCCURRENCES OF '&1' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V1.
                      REPLACE ALL OCCURRENCES OF '&2' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V2.
                      REPLACE ALL OCCURRENCES OF '&3' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V3.
                      REPLACE ALL OCCURRENCES OF '&4' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V4.
                    ELSE.
                      REPLACE FIRST OCCURRENCE OF '&' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V1.
                      REPLACE FIRST OCCURRENCE OF '&' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V2.
                      REPLACE FIRST OCCURRENCE OF '&' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V3.
                      REPLACE FIRST OCCURRENCE OF '&' IN XERR_MESSAGE WITH WA_RETURN2-MESSAGE_V4.
                    ENDIF.
                    CONDENSE XERR_MESSAGE.
                  ENDIF.
                ENDIF.
                IF XCONCAT_ERR IS INITIAL.
                  XCONCAT_ERR = XERR_MESSAGE.
                ELSE.
                  CONCATENATE XCONCAT_ERR XERR_MESSAGE INTO XCONCAT_ERR SEPARATED BY SPACE.
                ENDIF.
              ENDLOOP.
              IF XERR_INDI IS NOT INITIAL.
                CLEAR WA_ERR_TAB.
                WA_ERR_TAB-MATNR    = WA_MASTER_UPL-MATNR.
                WA_ERR_TAB-ZERR_LOG = XCONCAT_ERR.
                APPEND WA_ERR_TAB TO ERR_TAB.
                EXIT.
              ELSE.
                CALL FUNCTION 'BAPI_TRANSACTION_COMMIT' EXPORTING WAIT = 'X'.
              ENDIF.
            ENDIF.
          ENDIF.
        ENDLOOP.

      ELSEIF RSBIN IS NOT INITIAL.
        REFRESH: I_STORAGE_UPL.
        CLEAR: WA_STORAGE_UPL.
        FILENAME = UP_FILE.
        CALL FUNCTION 'TEXT_CONVERT_XLS_TO_SAP'
          EXPORTING I_LINE_HEADER        = 'X'
                    I_TAB_RAW_DATA       = IT_TYPE
                    I_FILENAME           = P_INFILE2
          TABLES    I_TAB_CONVERTED_DATA = I_STORAGE_UPL[]
          EXCEPTIONS CONVERSION_FAILED   = 1 OTHERS = 2.
        IF SY-SUBRC NE 0.
          MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
        ENDIF.
        IF I_STORAGE_UPL[] IS NOT INITIAL.
          SELECT * FROM LAGP INTO CORRESPONDING FIELDS OF TABLE I_LAGP
            FOR ALL ENTRIES IN I_STORAGE_UPL
            WHERE LGNUM EQ I_STORAGE_UPL-LGNUM
              AND LGTYP EQ I_STORAGE_UPL-LGTYP
              AND LGPLA EQ I_STORAGE_UPL-LGPLA.
        ENDIF.
        LOOP AT I_STORAGE_UPL INTO WA_STORAGE_UPL.
          READ TABLE I_LAGP WITH KEY LGNUM = WA_STORAGE_UPL-LGNUM
                                     LGTYP = WA_STORAGE_UPL-LGTYP
                                     LGPLA = WA_STORAGE_UPL-LGPLA
                            TRANSPORTING NO FIELDS.
          IF SY-SUBRC EQ 0.
            MOVE-CORRESPONDING WA_STORAGE_UPL TO WA_ERR_TAB.
            WA_ERR_TAB-ZERR_LOG = TEXT-E02.
            APPEND WA_ERR_TAB TO ERR_TAB.
            CONTINUE.
          ENDIF.
          MOVE-CORRESPONDING WA_STORAGE_UPL TO WA_LAGP.
          REFRESH: BDCDATA.
          PERFORM BDC_DYNPRO USING 'SAPML01S' '0400'.
          PERFORM BDC_FIELD  USING 'BDC_CURSOR' 'LAGP-LGPLA'.
          PERFORM BDC_FIELD  USING 'BDC_OKCODE' '/00'.
          PERFORM BDC_FIELD  USING 'LAGP-LGNUM' WA_STORAGE_UPL-LGNUM.
          PERFORM BDC_FIELD  USING 'LAGP-LGTYP' WA_STORAGE_UPL-LGTYP.
          PERFORM BDC_FIELD  USING 'LAGP-LGPLA' WA_STORAGE_UPL-LGPLA.
          PERFORM BDC_DYNPRO USING 'SAPML01S' '0400'.
          PERFORM BDC_FIELD  USING 'BDC_CURSOR' 'LAGP-LGPLA'.
          PERFORM BDC_FIELD  USING 'BDC_OKCODE' '/00'.
          PERFORM BDC_FIELD  USING 'LAGP-LGBER' WA_STORAGE_UPL-LGBER.
          PERFORM BDC_DYNPRO USING 'SAPML01S' '0400'.
          PERFORM BDC_FIELD  USING 'BDC_CURSOR' 'LAGP-LGPLA'.
          PERFORM BDC_FIELD  USING 'BDC_OKCODE' '=BU'.
          CLEAR CTUPARAMS.
          CTUPARAMS-DISMODE = 'N'.
          CTUPARAMS-UPDMODE = 'S'.
          CTUPARAMS-NOBINPT = 'X'.
          CALL TRANSACTION 'LS01N' USING BDCDATA OPTIONS FROM CTUPARAMS MESSAGES INTO MESSTAB.
          IF SY-SUBRC EQ 0.
            CALL FUNCTION 'BAPI_TRANSACTION_COMMIT' EXPORTING WAIT = 'X'.
          ELSE.
            ROLLBACK WORK.
            PERFORM G_ERR_SHDB CHANGING WMESSAGE.
            MOVE-CORRESPONDING WA_STORAGE_UPL TO WA_ERR_TAB.
            WA_ERR_TAB-ZERR_LOG = WMESSAGE.
            APPEND WA_ERR_TAB TO ERR_TAB.
          ENDIF.
        ENDLOOP.

      ELSE.
        REFRESH: TEMP_TAB, UPLOAD_TAB, ERR_TAB, I_MARA, I_T001W,
                 I_COLLECT_MATERIAL, I_T001L, I_COLLECT, I_T320.
        FILENAME = UP_FILE.
        CALL FUNCTION 'TEXT_CONVERT_XLS_TO_SAP'
          EXPORTING I_LINE_HEADER        = 'X'
                    I_TAB_RAW_DATA       = IT_TYPE
                    I_FILENAME           = P_INFILE2
          TABLES    I_TAB_CONVERTED_DATA = TEMP_TAB
          EXCEPTIONS CONVERSION_FAILED   = 1 OTHERS = 2.
        IF SY-SUBRC NE 0.
          MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
        ENDIF.
        LOOP AT TEMP_TAB INTO WA_TEMP_TAB.
          CLEAR WA_UPLOAD_TAB.
          WA_UPLOAD_TAB-MATNR = WA_TEMP_TAB-CLM_0001.
          IF RLGORT IS NOT INITIAL.
            WA_UPLOAD_TAB-WERKS = WA_TEMP_TAB-CLM_0002.
            WA_UPLOAD_TAB-LGORT = WA_TEMP_TAB-CLM_0003.
          ELSEIF RLGNUM IS NOT INITIAL.
            WA_UPLOAD_TAB-WERKS = WA_TEMP_TAB-CLM_0002.
            WA_UPLOAD_TAB-LGNUM = WA_TEMP_TAB-CLM_0003.
          ELSEIF RKZWSM IS NOT INITIAL.
            WA_UPLOAD_TAB-KZWSM = WA_TEMP_TAB-CLM_0002.
            WA_UPLOAD_TAB-ATNAM = WA_TEMP_TAB-CLM_0003.
            WA_UPLOAD_TAB-ATWRT = WA_TEMP_TAB-CLM_0004.
            WA_UPLOAD_TAB-WSMEI = WA_TEMP_TAB-CLM_0005.
          ELSEIF RQUALITY IS NOT INITIAL.
            WA_UPLOAD_TAB-WERKS   = WA_TEMP_TAB-CLM_0014.
            WA_UPLOAD_TAB-INSPTYPE = WA_TEMP_TAB-CLM_0096.
          ENDIF.
          APPEND WA_UPLOAD_TAB TO UPLOAD_TAB.
        ENDLOOP.

        LOOP AT UPLOAD_TAB INTO WA_UPLOAD_TAB.
          XTABIX = SY-TABIX.
          TRANSLATE WA_UPLOAD_TAB-MATNR TO UPPER CASE.
          CALL FUNCTION 'CONVERSION_EXIT_MATN1_INPUT'
            EXPORTING INPUT        = WA_UPLOAD_TAB-MATNR
            IMPORTING OUTPUT       = WA_UPLOAD_TAB-MATNR
            EXCEPTIONS LENGTH_ERROR = 1 OTHERS = 2.
          CALL FUNCTION 'CONVERSION_EXIT_CUNIT_INPUT'
            EXPORTING INPUT          = WA_UPLOAD_TAB-WSMEI
            IMPORTING OUTPUT         = WA_UPLOAD_TAB-WSMEI
            EXCEPTIONS UNIT_NOT_FOUND = 1 OTHERS = 2.
          MODIFY UPLOAD_TAB FROM WA_UPLOAD_TAB INDEX XTABIX.
          MOVE-CORRESPONDING WA_UPLOAD_TAB TO WA_COLLECT.
          COLLECT WA_COLLECT INTO I_COLLECT.
          MOVE-CORRESPONDING WA_UPLOAD_TAB TO WA_COLLECT_MATERIAL.
          COLLECT WA_COLLECT_MATERIAL INTO I_COLLECT_MATERIAL.
        ENDLOOP.

        IF UPLOAD_TAB[] IS NOT INITIAL.
          SELECT * FROM MARA INTO CORRESPONDING FIELDS OF TABLE I_MARA
            FOR ALL ENTRIES IN UPLOAD_TAB WHERE MATNR EQ UPLOAD_TAB-MATNR.
          SELECT * FROM T001W INTO CORRESPONDING FIELDS OF TABLE I_T001W
            FOR ALL ENTRIES IN UPLOAD_TAB WHERE WERKS EQ UPLOAD_TAB-WERKS.
          SELECT * FROM T001L INTO CORRESPONDING FIELDS OF TABLE I_T001L
            FOR ALL ENTRIES IN UPLOAD_TAB
            WHERE WERKS EQ UPLOAD_TAB-WERKS AND LGORT EQ UPLOAD_TAB-LGORT.
          SELECT * FROM T320 INTO CORRESPONDING FIELDS OF TABLE I_T320
            FOR ALL ENTRIES IN UPLOAD_TAB
            WHERE WERKS EQ UPLOAD_TAB-WERKS AND LGNUM EQ UPLOAD_TAB-LGNUM.
        ENDIF.

        SORT UPLOAD_TAB BY MATNR WERKS LGORT LGNUM.
        DELETE ADJACENT DUPLICATES FROM UPLOAD_TAB COMPARING ALL FIELDS.

        IF RLGORT IS NOT INITIAL.
          LOOP AT I_COLLECT INTO WA_COLLECT.
            REFRESH: BDCDATA.
            CLEAR: XEXIST.
            PERFORM BDC_DYNPRO USING 'SAPMM03M' '0105'.
            PERFORM BDC_FIELD  USING 'BDC_CURSOR' 'RM03M-MATNR'.
            PERFORM BDC_FIELD  USING 'BDC_OKCODE' '/00'.
            PERFORM BDC_FIELD  USING 'RM03M-MATNR' WA_UPLOAD_TAB-MATNR.
            PERFORM BDC_FIELD  USING 'RM03M-WERKS'  WA_UPLOAD_TAB-WERKS.
            PERFORM BDC_FIELD  USING 'RM03M-LFLAG'  'X'.
            LOOP AT UPLOAD_TAB INTO WA_UPLOAD_TAB
              WHERE MATNR EQ WA_COLLECT-MATNR AND WERKS EQ WA_COLLECT-WERKS.
              READ TABLE I_MARA WITH KEY MATNR = WA_UPLOAD_TAB-MATNR TRANSPORTING NO FIELDS.
              IF SY-SUBRC NE 0.
                MOVE-CORRESPONDING WA_UPLOAD_TAB TO WA_ERR_TAB.
                WA_ERR_TAB-ZERR_LOG = 'Invalid Material Number'.
                APPEND WA_ERR_TAB TO ERR_TAB. CONTINUE.
              ENDIF.
              READ TABLE I_T001W WITH KEY WERKS = WA_UPLOAD_TAB-WERKS TRANSPORTING NO FIELDS.
              IF SY-SUBRC NE 0.
                MOVE-CORRESPONDING WA_UPLOAD_TAB TO WA_ERR_TAB.
                WA_ERR_TAB-ZERR_LOG = 'Invalid Plant'.
                APPEND WA_ERR_TAB TO ERR_TAB. CONTINUE.
              ENDIF.
              READ TABLE I_T001L WITH KEY WERKS = WA_UPLOAD_TAB-WERKS
                                           LGORT = WA_UPLOAD_TAB-LGORT
                                 TRANSPORTING NO FIELDS.
              IF SY-SUBRC NE 0.
                MOVE-CORRESPONDING WA_UPLOAD_TAB TO WA_ERR_TAB.
                WA_ERR_TAB-ZERR_LOG = 'Invalid Storage Location'.
                APPEND WA_ERR_TAB TO ERR_TAB. CONTINUE.
              ENDIF.
              PERFORM BDC_DYNPRO USING 'SAPMM03M' '0195'.
              PERFORM BDC_FIELD  USING 'BDC_CURSOR' 'RM03M-LGORT(10)'.
              PERFORM BDC_FIELD  USING 'BDC_OKCODE' '=P++'.
              PERFORM BDC_DYNPRO USING 'SAPMM03M' '0195'.
              PERFORM BDC_FIELD  USING 'BDC_CURSOR' 'RM03M-LGORT(10)'.
              PERFORM BDC_FIELD  USING 'BDC_OKCODE' '/00'.
              PERFORM BDC_FIELD  USING 'RM03M-LGORT(10)' WA_UPLOAD_TAB-LGORT.
              XEXIST = 'X'.
            ENDLOOP.
            PERFORM BDC_DYNPRO USING 'SAPMM03M' '0195'.
            PERFORM BDC_FIELD  USING 'BDC_CURSOR' 'RM03M-MATNR'.
            PERFORM BDC_FIELD  USING 'BDC_OKCODE' '=BU'.
            IF XEXIST IS NOT INITIAL.
              CLEAR CTUPARAMS.
              CTUPARAMS-DISMODE = CTUMODE.
              CTUPARAMS-UPDMODE = 'S'.
              CTUPARAMS-NOBINPT = 'X'.
              CALL TRANSACTION 'MMSC' USING BDCDATA OPTIONS FROM CTUPARAMS MESSAGES INTO MESSTAB.
              IF SY-SUBRC EQ 0.
                COMMIT WORK AND WAIT.
              ELSE.
                ROLLBACK WORK.
                PERFORM G_ERR_SHDB CHANGING WMESSAGE.
                LOOP AT UPLOAD_TAB INTO WA_UPLOAD_TAB
                  WHERE MATNR EQ WA_COLLECT-MATNR AND WERKS EQ WA_COLLECT-WERKS.
                  MOVE-CORRESPONDING WA_UPLOAD_TAB TO WA_ERR_TAB.
                  WA_ERR_TAB-ZERR_LOG = WMESSAGE.
                  APPEND WA_ERR_TAB TO ERR_TAB.
                ENDLOOP.
              ENDIF.
            ENDIF.
          ENDLOOP.

        ELSEIF RLGNUM IS NOT INITIAL.
          LOOP AT UPLOAD_TAB INTO WA_UPLOAD_TAB.
            CLEAR: HEADDATA, PLANTDATA, WAREHOUSENUMBERDATA,
                   PLANTDATAX, WAREHOUSENUMBERDATAX, RETURN.
            REFRESH: RETURNMES.
            HEADDATA-MATERIAL_LONG  = WA_UPLOAD_TAB-MATNR.
            HEADDATA-WAREHOUSE_VIEW = 'X'.
            PLANTDATA-PLANT              = WA_UPLOAD_TAB-WERKS.
            PLANTDATAX-PLANT             = WA_UPLOAD_TAB-WERKS.
            WAREHOUSENUMBERDATA-WHSE_NO  = WA_UPLOAD_TAB-LGNUM.
            WAREHOUSENUMBERDATAX-WHSE_NO = WA_UPLOAD_TAB-LGNUM.
            CALL FUNCTION 'BAPI_MATERIAL_SAVEDATA'
              EXPORTING
                HEADDATA             = HEADDATA
                PLANTDATA            = PLANTDATA
                PLANTDATAX           = PLANTDATAX
                WAREHOUSENUMBERDATA  = WAREHOUSENUMBERDATA
                WAREHOUSENUMBERDATAX = WAREHOUSENUMBERDATAX
              IMPORTING RETURN       = RETURN
              TABLES    RETURNMESSAGES = RETURNMES.
            CALL FUNCTION 'BAPI_TRANSACTION_COMMIT' EXPORTING WAIT = 'X'.
            IF RETURN-TYPE = 'E'.
              CLEAR WMESSAGE.
              LOOP AT RETURNMES INTO WA_RETURNMES WHERE TYPE EQ 'E'.
                CONCATENATE WMESSAGE WA_RETURNMES-MESSAGE
                  INTO WMESSAGE SEPARATED BY SPACE.
                CONDENSE WMESSAGE.
              ENDLOOP.
              MOVE-CORRESPONDING WA_UPLOAD_TAB TO WA_ERR_TAB.
              WA_ERR_TAB-ZERR_LOG = WMESSAGE.
              APPEND WA_ERR_TAB TO ERR_TAB.
            ENDIF.
          ENDLOOP.

        ELSEIF RKZWSM IS NOT INITIAL.
          LOOP AT I_COLLECT_MATERIAL INTO WA_COLLECT_MATERIAL.
            REFRESH: I_MEINH_WS_UPD, I_MEINH_WS_UPDX, I_RETURN.
            CLEAR: XERR_INDI.
            LOOP AT UPLOAD_TAB INTO WA_UPLOAD_TAB
              WHERE MATNR EQ WA_COLLECT_MATERIAL-MATNR.
              CLEAR: WA_MEINH_WS_UPD, WA_MEINH_WS_UPDX.
              WA_MEINH_WS_UPD-WSMEI = WA_UPLOAD_TAB-WSMEI.
              WA_MEINH_WS_UPD-ATNAM = WA_UPLOAD_TAB-ATNAM.
              WA_MEINH_WS_UPD-ATWRT = WA_UPLOAD_TAB-ATWRT.
              APPEND WA_MEINH_WS_UPD TO I_MEINH_WS_UPD.
              WA_MEINH_WS_UPDX-WSMEI = WA_UPLOAD_TAB-WSMEI.
              WA_MEINH_WS_UPDX-ATNAM = 'X'.
              WA_MEINH_WS_UPDX-ATWRT = 'X'.
              APPEND WA_MEINH_WS_UPDX TO I_MEINH_WS_UPDX.
            ENDLOOP.
            CALL FUNCTION 'VBWS_UOM_MAINTAIN_DARK'
              EXPORTING
                I_MATNR         = WA_COLLECT_MATERIAL-MATNR
                I_KZWSM         = WA_UPLOAD_TAB-KZWSM
                I_KZWSMX        = 'X'
                I_NO_UPDATE     = ' '
              TABLES
                I_MEINH_WS_UPD  = I_MEINH_WS_UPD
                I_MEINH_WS_UPDX = I_MEINH_WS_UPDX
                E_RETURN        = I_RETURN
              EXCEPTIONS ERROR  = 1 OTHERS = 2.
            LOOP AT I_RETURN INTO WA_RETURN WHERE TYPE EQ 'E'.
              XERR_INDI = 'X'.
              WA_ERR_TAB-MATNR    = WA_COLLECT_MATERIAL-MATNR.
              WA_ERR_TAB-ZERR_LOG = WA_RETURN-MESSAGE.
              APPEND WA_ERR_TAB TO ERR_TAB.
              EXIT.
            ENDLOOP.
            IF XERR_INDI IS INITIAL.
              CALL FUNCTION 'BAPI_TRANSACTION_COMMIT' EXPORTING WAIT = 'X'.
            ENDIF.
          ENDLOOP.

        ELSEIF RQUALITY IS NOT INITIAL.
          LOOP AT UPLOAD_TAB INTO WA_UPLOAD_TAB.
            DATA: STATM TYPE MSTA-STATM.
            CLEAR: STATM.
            IF WA_UPLOAD_TAB-MATNR IS NOT INITIAL.
              SELECT SINGLE STATM FROM MSTA INTO STATM
                WHERE MATNR EQ WA_UPLOAD_TAB-MATNR
                  AND WERKS EQ WA_UPLOAD_TAB-WERKS
                  AND STATM EQ 'Q'.
              IF STATM IS NOT INITIAL.
                REFRESH: INSPECTIONCTRL, RETURN_QM.
                CLEAR  : GW_INSPECTIONCTRL, GW_RETURN_QM, XCONCAT_ERR.
                GW_INSPECTIONCTRL-INSPTYPE                  = WA_UPLOAD_TAB-INSPTYPE.
                GW_INSPECTIONCTRL-MATERIAL                  = WA_UPLOAD_TAB-MATNR.
                GW_INSPECTIONCTRL-PLANT                     = WA_UPLOAD_TAB-WERKS.
                GW_INSPECTIONCTRL-IND_INSP_WITH_TSK_LIST    = 'X'.
                GW_INSPECTIONCTRL-QUAL_SCORE_PROCEDURE      = '06'.
                GW_INSPECTIONCTRL-IND_INSPTYPE_MAT_ACTIVE   = 'X'.
                IF WA_UPLOAD_TAB-INSPTYPE EQ '04'.
                  GW_INSPECTIONCTRL-IND_POST_TO_INSP_STOCK  = 'X'.
                ENDIF.
                GW_INSPECTIONCTRL-IND_AUTO_ASSIGN           = 'X'.
                GW_INSPECTIONCTRL-IND_SKIPS_ALLOWED         = 'X'.
                GW_INSPECTIONCTRL-IND_AUTOMATIC_UD          = 'X'.
                GW_INSPECTIONCTRL-IND_INSP_BY_CHARAC        = 'X'.
                GW_INSPECTIONCTRL-IND_SINGLE_UNITS_POSSIBLE = 'X'.
                APPEND GW_INSPECTIONCTRL TO INSPECTIONCTRL.
                CLEAR  GW_INSPECTIONCTRL.
                CALL FUNCTION 'BAPI_MATINSPCTRL_SAVEREPLICA'
                  TABLES RETURN         = RETURN_QM
                         INSPECTIONCTRL = INSPECTIONCTRL.
                IF RETURN_QM[] IS INITIAL.
                  CALL FUNCTION 'BAPI_TRANSACTION_COMMIT' EXPORTING WAIT = 'X'.
                ELSE.
                  CLEAR: WA_ERR_TAB, XCONCAT_ERR.
                  LOOP AT RETURN_QM INTO GW_RETURN_QM.
                    CONCATENATE GW_RETURN_QM-MESSAGE GW_RETURN_QM-MESSAGE_V1
                      GW_RETURN_QM-MESSAGE_V2 INTO XCONCAT_ERR SEPARATED BY ' '.
                    WA_ERR_TAB-MATNR    = WA_UPLOAD_TAB-MATNR.
                    WA_ERR_TAB-ZERR_LOG = XCONCAT_ERR.
                    APPEND WA_ERR_TAB TO ERR_TAB.
                    CLEAR WA_ERR_TAB. EXIT.
                  ENDLOOP.
                ENDIF.
              ENDIF.
            ENDIF.
          ENDLOOP.
        ENDIF.
      ENDIF.

      IF ERR_TAB[] IS NOT INITIAL.
        DESCRIBE TABLE ERR_TAB LINES TC_0100-LINES.
        IF TC_0100-TOP_LINE GT TC_0100-LINES.
          TC_0100-TOP_LINE = 1.
        ENDIF.
        CALL SCREEN 0100.
      ELSE.
        MESSAGE TEXT-S01 TYPE 'S'.
      ENDIF.
  ENDCASE.
ENDMODULE.                 " USER_COMMAND_0010  INPUT

*&---------------------------------------------------------------------*
*&      Form  G_ERR_SHDB
*&---------------------------------------------------------------------*
@ini 
FORM G_ERR_SHDB CHANGING P_REMARK.
  DATA: P_TEXT(255), W_LASTIDX TYPE SY-TABIX.
  DESCRIBE TABLE MESSTAB LINES W_LASTIDX.
  READ TABLE MESSTAB INDEX W_LASTIDX.
  IF SY-SUBRC EQ 0.
    SELECT SINGLE * FROM T100 WHERE SPRSL = MESSTAB-MSGSPRA
                                AND ARBGB = MESSTAB-MSGID
                                AND MSGNR = MESSTAB-MSGNR.
    IF SY-SUBRC = 0.
      CONCATENATE P_TEXT T100-TEXT INTO P_TEXT.
      IF P_TEXT CS '&1'.
        REPLACE ALL OCCURRENCES OF '&1' IN P_TEXT WITH MESSTAB-MSGV1.
        REPLACE ALL OCCURRENCES OF '&2' IN P_TEXT WITH MESSTAB-MSGV2.
        REPLACE ALL OCCURRENCES OF '&3' IN P_TEXT WITH MESSTAB-MSGV3.
        REPLACE ALL OCCURRENCES OF '&4' IN P_TEXT WITH MESSTAB-MSGV4.
      ELSE.
        REPLACE FIRST OCCURRENCE OF '&' IN P_TEXT WITH MESSTAB-MSGV1.
        REPLACE FIRST OCCURRENCE OF '&' IN P_TEXT WITH MESSTAB-MSGV2.
        REPLACE FIRST OCCURRENCE OF '&' IN P_TEXT WITH MESSTAB-MSGV3.
        REPLACE FIRST OCCURRENCE OF '&' IN P_TEXT WITH MESSTAB-MSGV4.
      ENDIF.
      CONDENSE P_TEXT.
    ENDIF.
  ENDIF.
  P_REMARK = P_TEXT.
ENDFORM.                    " G_ERR_SHDB

*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_0100  INPUT
*&---------------------------------------------------------------------*
MODULE USER_COMMAND_0100 INPUT.
  CASE SAVE_CODE.
    WHEN 'EXECUTE'.
      PERFORM SAVE_XLS.
    WHEN OTHERS.
  ENDCASE.
ENDMODULE.                 " USER_COMMAND_0100  INPUT

*&---------------------------------------------------------------------*
*&      Form  SAVE_XLS
*&---------------------------------------------------------------------*
FORM SAVE_XLS.
  DATA: LV_FILENAME  TYPE STRING,
        LV_FILENAME2 TYPE RLGRAP-FILENAME,
        GV_PATH_INI  TYPE STRING,
        GV_PATH_SEL  TYPE STRING.

  CALL METHOD CL_GUI_FRONTEND_SERVICES=>DIRECTORY_BROWSE
    EXPORTING  INITIAL_FOLDER  = GV_PATH_INI
    CHANGING   SELECTED_FOLDER = GV_PATH_SEL
    EXCEPTIONS CNTL_ERROR      = 1 ERROR_NO_GUI = 2 OTHERS = 3.
  IF SY-SUBRC = 0.
    CALL METHOD CL_GUI_CFW=>FLUSH( ).
    IF NOT GV_PATH_SEL IS INITIAL.
      GV_PATH_INI = GV_PATH_SEL.
    ENDIF.
  ENDIF.

  CLEAR LV_FILENAME.
  LV_FILENAME  = GV_PATH_INI.
  LV_FILENAME2 = LV_FILENAME.
  CONCATENATE LV_FILENAME '/Error_' 'Material_Master ' '.xls' INTO LV_FILENAME.

  CALL FUNCTION 'GUI_DOWNLOAD'
    EXPORTING FILENAME             = LV_FILENAME
              FILETYPE             = 'ASC'
              WRITE_FIELD_SEPARATOR = 'X'
    TABLES    DATA_TAB             = ERR_TAB.
ENDFORM.                    " SAVE_XLS

*&=====================================================================*
*& FORM-FORM UNTUK DOWNLOAD TEMPLATE
*&=====================================================================*

*&---------------------------------------------------------------------*
*&      Form  DOWNLOAD_TEMPLATE
*&---------------------------------------------------------------------*
FORM DOWNLOAD_TEMPLATE.
  DATA: LV_HEADER   TYPE STRING,
        LV_PATH     TYPE STRING,
        LV_FILENAME TYPE STRING,
        LV_FULLPATH TYPE STRING,
        LV_ACTION   TYPE I,
        LT_DATA     TYPE STANDARD TABLE OF STRING.

  REFRESH LT_DATA.
  CLEAR: LV_HEADER, LV_FILENAME.

* Tentukan header & nama file sesuai radio button
  IF RLGORT IS NOT INITIAL.
    LV_FILENAME = 'Template_YMMI004_Storage_Location.xls'.
    LV_HEADER = 'Material Number'  && CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB
             && 'Plant'            && CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB
             && 'Storage Location'.

  ELSEIF RLGNUM IS NOT INITIAL.
    LV_FILENAME = 'Template_YMMI004_Warehouse_Number.xls'.
    LV_HEADER = 'Material Number'  && CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB
             && 'Plant'            && CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB
             && 'Warehouse Number'.

  ELSEIF RMATERIAL IS NOT INITIAL.
    LV_FILENAME = 'Template_YMMI004_Material_Master.xls'.
    PERFORM BUILD_HEADER_MATERIAL CHANGING LV_HEADER.

  ELSEIF RSBIN IS NOT INITIAL.
    LV_FILENAME = 'Template_YMMI004_Storage_Bin.xls'.
    LV_HEADER = 'Warehouse Number' && CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB
             && 'Storage Type'     && CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB
             && 'Storage Bin'      && CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB
             && 'Storage Section'.

  ELSEIF RQUALITY IS NOT INITIAL.
    LV_FILENAME = 'Template_YMMI004_Quality_Management.xls'.
    PERFORM BUILD_HEADER_QUALITY CHANGING LV_HEADER.

  ELSEIF RKZWSM IS NOT INITIAL.
    LV_FILENAME = 'Template_YMMI004_Unit_of_Measure.xls'.
    LV_HEADER = 'Material Number'      && CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB
             && 'UoM Usage Indicator'  && CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB
             && 'Characteristic Name'  && CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB
             && 'Characteristic Value' && CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB
             && 'Batch Specific UoM'.

  ELSE.
    MESSAGE 'Pilih salah satu mode upload terlebih dahulu.' TYPE 'I'.
    RETURN.
  ENDIF.

  APPEND LV_HEADER TO LT_DATA.

* Dialog simpan file
  CALL METHOD CL_GUI_FRONTEND_SERVICES=>FILE_SAVE_DIALOG
    EXPORTING
      DEFAULT_EXTENSION = 'XLS'
      DEFAULT_FILE_NAME = LV_FILENAME
      FILE_FILTER       = 'Excel Files (*.xls)|*.xls|All Files (*.*)|*.*'
    CHANGING
      FILENAME          = LV_FILENAME
      PATH              = LV_PATH
      FULLPATH          = LV_FULLPATH
      USER_ACTION       = LV_ACTION
    EXCEPTIONS
      CNTL_ERROR        = 1
      ERROR_NO_GUI      = 2
      OTHERS            = 3.

  IF SY-SUBRC <> 0 OR LV_ACTION = 1.  " 1 = user cancel
    RETURN.
  ENDIF.

  CALL FUNCTION 'GUI_DOWNLOAD'
    EXPORTING
      FILENAME                = LV_FULLPATH
      FILETYPE                = 'ASC'
      WRITE_FIELD_SEPARATOR   = CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB
    TABLES
      DATA_TAB                = LT_DATA
    EXCEPTIONS
      FILE_WRITE_ERROR        = 1
      NO_BATCH                = 2
      GUI_REFUSE_FILETRANSFER = 3
      OTHERS                  = 4.

  IF SY-SUBRC = 0.
    CONCATENATE 'Template berhasil didownload: ' LV_FULLPATH
      INTO LV_FULLPATH SEPARATED BY SPACE.
    MESSAGE LV_FULLPATH TYPE 'S'.
  ELSE.
    MESSAGE 'Gagal mendownload template.' TYPE 'E'.
  ENDIF.
ENDFORM.                    " DOWNLOAD_TEMPLATE

*&---------------------------------------------------------------------*
*&      Form  BUILD_HEADER_MATERIAL
*&  Urutan kolom mengikuti persis urutan field di TY_MASTER_UPL
*&---------------------------------------------------------------------*
FORM BUILD_HEADER_MATERIAL CHANGING PV_HEADER TYPE STRING.
  TYPES: BEGIN OF TY_HDR,
           FIELDN TYPE STRING,
           LABEL  TYPE STRING,
         END OF TY_HDR.

  DATA: LT_HDR TYPE STANDARD TABLE OF TY_HDR,
        WA_HDR TYPE TY_HDR,
        LV_TAB TYPE STRING.

  LV_TAB = CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.

  DEFINE ADD_HDR.
    WA_HDR-FIELDN = &1.
    WA_HDR-LABEL  = &2.
    APPEND WA_HDR TO LT_HDR.
  END-OF-DEFINITION.

* ===== BASIC DATA =====
  ADD_HDR: 'MATNR'      'Material Number',
           'MBRSH'      'Industry Sector',
           'BISMT'      'Old Material Number',
           'MTART'      'Material Type',
           'MATKL'      'Material Group',
           'MEINS'      'Base Unit of Measure',
           'MAKTX'      'Material Description',
           'SPART'      'Division',
           'MTPOS_MARA' 'General Item Category Group',
           'FERTH'      'Basic Material',
           'ZEINR'      'Document Number',
           'NORMT'      'Standard Description',
           'GROES'      'Size/Dimensions'.

* ===== PLANT / SLOC =====
  ADD_HDR: 'WERKS'      'Plant',
           'LGORT'      'Storage Location'.

* ===== SALES ORG 1 =====
  ADD_HDR: 'VKORG'      'Sales Organization',
           'VTWEG'      'Distribution Channel',
           'DWERK'      'Delivering Plant',
           'VRKME'      'Sales Unit',
           'HERKL'      'Country of Origin',
           'TAXM1'      'Tax Classification',
           'TATY1'      'Tax Type'.

* ===== SALES ORG 2 =====
  ADD_HDR: 'MTPOS'      'Item Category Group',
           'KTGRM'      'Account Assignment Group',
           'MVGR1'      'Material Group 1',
           'MVGR2'      'Material Group 2',
           'MVGR3'      'Material Group 3',
           'MVGR4'      'Material Group 4',
           'MVGR5'      'Material Group 5'.

* ===== SALES: GENERAL/PLANT =====
  ADD_HDR: 'TRAGR'      'Transportation Group',
           'LADGR'      'Loading Group',
           'MAGRV'      'Material Group Shipping',
           'VHART'      'Shipping Material Type',
           'XCHPF'      'Batch Management',
           'PRCTR'      'Profit Center'.

* ===== ACCOUNTING 1 =====
  ADD_HDR: 'BKLAS'      'Valuation Class',
           'STPRS'      'Standard Price',
           'VERPR'      'Moving Average Price',
           'PEINH'      'Price Unit',
           'VPRSV'      'Price Control',
           'PEINH_2'    'Price Unit (Hard Currency)'.

* ===== ADDITIONAL DATA / UOM =====
  ADD_HDR: 'UMREN'      'Denominator',
           'MEINH'      'Alternative Unit of Measure',
           'UMREZ'      'Numerator',
           'LAENG'      'Length',
           'BREIT'      'Width',
           'HOEHE'      'Height',
           'MEABM'      'Unit of Dimension',
           'BRGEW'      'Gross Weight',
           'GEWEI'      'Weight Unit',
           'NTGEW'      'Net Weight',
           'VOLUM'      'Volume',
           'EKGRP'      'Purchasing Group',
           'VOLEH'      'Volume Unit',
           'KZWSM'      'UoM Usage Indicator'.

* ===== CLASSIFICATION =====
  ADD_HDR: 'CLASS'      'Class',
           'WARNA'      'Color',
           'VOL_PROD'   'Product Volume'.

* ===== MRP 1 =====
  ADD_HDR: 'DISMM'      'MRP Type',
           'DISGR'      'MRP Group',
           'DISPO'      'MRP Controller',
           'DISLS'      'Lot Size Key',
           'BSTMI'      'Minimum Lot Size',
           'BSTMA'      'Maximum Lot Size',
           'BSTRF'      'Rounding Value'.

* ===== MRP 2 =====
  ADD_HDR: 'BESKZ'      'Procurement Type',
           'SOBSL'      'Special Procurement',
           'RGEKZ'      'Backflush',
           'DZEIT'      'In-house Production Time',
           'PLIFZ'      'Planned Delivery Time',
           'WEBAZ'      'GR Processing Time',
           'FHORI'      'Scheduling Margin Key',
           'EISBE'      'Safety Stock'.

* ===== MRP 3 =====
  ADD_HDR: 'STRGR'      'Strategy Group',
           'VRMOD'      'Consumption Mode',
           'VINT2'      'Forward Consumption Period',
           'VINT1'      'Backward Consumption Period',
           'PERKZ'      'Period Indicator',
           'PERIV'      'Fiscal Year Variant',
           'MTVFP'      'Availability Check'.

* ===== MRP 4 =====
  ADD_HDR: 'ALTSL'      'Alternative BOM',
           'SBDKZ'      'Dependent Requirement Indicator'.

* ===== WORK SCHEDULING =====
  ADD_HDR: 'AUSME'      'Unit of Issue',
           'LGPRO'      'Issuing Storage Location',
           'LGFSB'      'SLoc for External Procurement',
           'SFCPF'      'Production Scheduling Profile',
           'UNETO'      'Underdelivery Tolerance',
           'UEETO'      'Overdelivery Tolerance',
           'UEETK'      'Unlimited Overdelivery'.
*           'SERNP'      'Serial Number Profile'.

* ===== COSTING 1 =====
  ADD_HDR: 'HKMAT'      'Origin Material',
           'EKALR'      'Material Costed with Qty Structure',
           'LOSGR'      'Costing Lot Size',
           'NCOST'      'Do Not Cost'.

* ===== PLANT STATUS / OTHERS =====
  ADD_HDR: 'MMSTA'      'Plant-Specific Material Status',
           'EPRIO'      'Strategy Determination Group',
           'EXTWG'      'External Material Group'.

* ===== QUALITY MANAGEMENT =====
  ADD_HDR: 'INSPTYPE'                    'Inspection Type',
           'IND_INSP_WITH_TSK_LIST'      'Inspection With Task List',
           'IND_SPEC_MATSPEC'            'Insp. Spec from Material Spec',
           'IND_SPEC_CONFIG'             'Insp. Spec from Configuration',
           'IND_SPEC_BATCH'              'Insp. Spec from Batch',
           'IND_AUTO_ASSIGN'             'Automatic Spec Assignment',
           'IND_INSP_BY_CHARAC'          'Inspect by Characteristics',
           'IND_POST_TO_INSP_STOCK'      'Post to Inspection Stock',
           'IND_AUTOMATIC_UD'            'Automatic Usage Decision',
           'SAMPLING_PROCEDURE'          'Sampling Procedure',
           'DYN_MODIF_RULE'              'Dynamic Modification Rule',
           'INSP_PERCENTAGE'             'Inspection Percentage',
           'IND_100_PERCENT_INSPECTION'  '100% Inspection',
           'IND_SKIPS_ALLOWED'           'Skips Allowed',
           'IND_MANUAL_SAMPLE'           'Manual Sample Entry',
           'IND_MANUAL_SAMPLE_CALC'      'Manual Sample Calculation',
           'IND_SINGLE_UNITS_POSSIBLE'   'Serial Number Management',
           'AVE_INSP_DURATION'           'Average Inspection Duration',
           'CONTR_INSP_LOT_CREATE'       'Inspection Lot Creation Ctrl',
           'QUAL_SCORE_PROCEDURE'        'Quality Score Procedure',
           'ALLOWED_SCRAP_SHARE'         'Allowed Scrap Share (%)',
           'IND_SPECIAL_QM_ORDER'        'Individual QM Order',
           'QM_ORDERID'                  'QM Order Number',
           'IND_INSPTYPE_MAT_ACTIVE'     'Insp. Type-Material Active',
           'PREFERRED_INSPTYPE'          'Preferred Inspection Type',
           'INSPTYPE_DELETE'             'Inspection Type to Delete',
           'MATERIAL_EXTERNAL'           'Long Material Number',
           'MATERIAL_GUID'               'Material GUID',
           'MATERIAL_VERSION'            'Material Version',
           'IND_HU_INSPECTION'           'Inspection for Handling Unit',
           'MS_FLAG'                     'Multiple Specifications'.

  CLEAR PV_HEADER.
  LOOP AT LT_HDR INTO WA_HDR.
    IF PV_HEADER IS INITIAL.
      PV_HEADER = WA_HDR-LABEL.
    ELSE.
      CONCATENATE PV_HEADER LV_TAB WA_HDR-LABEL INTO PV_HEADER.
    ENDIF.
  ENDLOOP.
ENDFORM.                    " BUILD_HEADER_MATERIAL


*&---------------------------------------------------------------------*
*&      Form  BUILD_HEADER_QUALITY
*&  WERKS di kolom 14, INSPTYPE di kolom 96 (sesuai CLM_0014/CLM_0096)
*&---------------------------------------------------------------------*
FORM BUILD_HEADER_QUALITY CHANGING PV_HEADER TYPE STRING.
  DATA: LV_TAB TYPE STRING,
        LV_I   TYPE I.

  LV_TAB = CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.

* Kolom 1: Material Number
  PV_HEADER = 'Material Number'.

* Kolom 2-13: filler kosong (12 kolom)
  DO 12 TIMES.
    CONCATENATE PV_HEADER LV_TAB '' INTO PV_HEADER.
  ENDDO.

* Kolom 14: Plant
  CONCATENATE PV_HEADER LV_TAB 'Plant' INTO PV_HEADER.

* Kolom 15-95: filler kosong (81 kolom)
  DO 81 TIMES.
    CONCATENATE PV_HEADER LV_TAB '' INTO PV_HEADER.
  ENDDO.

* Kolom 96: Inspection Type
  CONCATENATE PV_HEADER LV_TAB 'Inspection Type' INTO PV_HEADER.
ENDFORM.                    " BUILD_HEADER_QUALITY
*}   REPLACE